### ISSUE TITLE
Batched 1d real-to-complex produces incorrect results

### ISSUE THREAD

**Issue by malcolmroberts** [clMathLibraries/clFFT#105]
When transforming an array of doubles of size nx*ny = 4*4 with a multiple 1D transform of length n=4 and batch size of N=4, the correct output is given with istride=1, idist=4, ostride=1, odist=3 (ie transforms in the second index), but the output is incorrect when one uses istride=4, idist=1, ostride=3, odist=1 (ie transforms in the first index).

A minimal example is given below.  The output of is:

transforms in the first index
nx: 4
ny: 4
n: 4
M: 4
istride: 4
idist: 1
ostride: 3
odist: 1

Input:
0 1 2 3 
10 11 12 13 
20 21 22 23 
30 31 32 33 

Output:
(60,0) (64,0) (68,0) 
(-20,20) (-20,20) (-20,20) 
(-20,20) (-20,0) (-20,0) 
(-20,0) (-nan,1.061e-313) (2.47033e-323,1.27825e-316) 

The source code for this output is:
#include <iostream>
#include <CL/cl.h>
#include <clFFT.h>

// Compile with:
// g++ -I$CLFFT_INCLUDE_PATH -L$CLFFT_LIB_PATH  mfft1reg.cpp -o mfft1reg -lclFFT -lOpenCL -lm

int main() {
  // size of real input array.
  int nx = 4;
  int ny = 4;

  int n = 4; // length of transform
  int M = 4; // number of transforms
  
#define HORIZONTAL 0
#if HORIZONTAL
  std::cout << "transforms in the second index" << std::endl;
  size_t istride = 1;
  size_t ostride = 1;
  size_t idist = 4; // n
  size_t odist = 3; // n / 2 + 1;
#else
  std::cout << "transforms in the first index" << std::endl;
  size_t istride = 4; // n
  size_t ostride = 3; // n / 2 + 1
  size_t idist = 1;
  size_t odist = 1;
#endif

  std::cout << "nx: " << nx << std::endl;
  std::cout << "ny: " << ny << std::endl;
  std::cout << "n: " << n << std::endl;
  std::cout << "M: " << M << std::endl;
  std::cout << "istride: " << istride << std::endl;
  std::cout << "idist: " << idist << std::endl;
  std::cout << "ostride: " << ostride << std::endl;
  std::cout << "odist: " << odist << std::endl;
  std::cout << std::endl;

  double *X = new double[nx * ny];

  // Initialize the array
  for(int ix = 0; ix < nx; ++ix) {
    for(int iy = 0; iy < ny; ++iy) {
      X[iy * nx + ix] = ix + 10 * iy;
    }
  }
  
  std::cout << "Input:" << std::endl;
  {
    int pos = 0;
    for(int ix = 0; ix < nx; ++ix) {
      for(int iy = 0; iy < ny; ++iy) {
	std::cout << X[pos] << " ";
	++pos;
      }
      std::cout << std::endl;
    }
    std::cout << std::endl;
  }

  cl_int ret;

  // OpenCL setup
  cl_platform_id platform = 0;
  cl_device_id device;
  ret = clGetPlatformIDs(1, &platform, NULL);
  ret = clGetDeviceIDs(platform, CL_DEVICE_TYPE_CPU, 1, &device, NULL);

  cl_context_properties props[3] = {CL_CONTEXT_PLATFORM, 0, 0};
  props[1] = (cl_context_properties) platform;
  cl_context ctx = clCreateContext(props, 1, &device, NULL, NULL, &ret);
  cl_command_queue queue = clCreateCommandQueue(ctx, device, 0, &ret);
  
  // clFFT setup
  clfftSetupData fftSetup;
  ret = clfftInitSetupData(&fftSetup);
  ret = clfftSetup(&fftSetup);
  
  // Plan setup
  size_t clLengths[1] = {n};
  clfftDim dim = CLFFT_1D;
  clfftPlanHandle plan;
  ret = clfftCreateDefaultPlan(&plan,
  			       ctx,
  			       dim,
  			       clLengths);
  
  ret = clfftSetPlanPrecision(plan, CLFFT_DOUBLE);
  ret = clfftSetLayout(plan,
		       CLFFT_REAL,
		       CLFFT_HERMITIAN_INTERLEAVED);
  ret = clfftSetResultLocation(plan, CLFFT_OUTOFPLACE);
  ret = clfftSetPlanInStride(plan, dim, &istride);
  ret = clfftSetPlanOutStride(plan, dim, &ostride);
  ret = clfftSetPlanDistance(plan, idist, odist);
  ret = clfftSetPlanBatchSize(plan, M); 

  ret = clfftBakePlan(plan, 1, &queue, NULL, NULL);

  cl_mem inbuf = clCreateBuffer(ctx,
				CL_MEM_READ_WRITE,
				nx * ny * sizeof(double),
				NULL,
				&ret);
  cl_mem outbuf = clCreateBuffer(ctx,
				 CL_MEM_READ_WRITE,
				 2 * (n / 2 + 1) * M * sizeof(double),
				 NULL,
				 &ret);

  size_t nwork = 0;
  ret = clfftGetTmpBufSize(plan, &nwork);
  cl_mem workmem = nwork > 0 ? 
    clCreateBuffer(ctx, CL_MEM_READ_WRITE, nwork, 0, &ret) : NULL;
  
  // Copy from ram to cl_mem
  ret = clEnqueueWriteBuffer(queue, inbuf, 
			     CL_TRUE, 0,
			     nx * ny * sizeof(double), X, 
			     0, 0, 0);

  // Enqueue transform
  ret = clfftEnqueueTransform(plan, // clfftPlanHandle plHandle,
			      CLFFT_FORWARD, //direction
			      1,  //cl_uint numQueuesAndEvents,
			      &queue,
			      0, // cl_uint numWaitEvents,
			      NULL, // const cl_event * waitEvents,
			      NULL, // cl_event * outEvents,
			      &inbuf, // cl_mem * inputBuffers,
			      &outbuf, // cl_mem * outputBuffers,
			      workmem // cl_mem tmpBuffer 
			      );

  // Copy from cl_mem to ram
  double *FX = new double[2 * (n / 2 + 1) * M];

  ret = clEnqueueReadBuffer(queue, outbuf,
			    CL_TRUE,
			    0,
			    2 * (n / 2 + 1) * M * sizeof(double), FX,
			    0, 0, 0);

  std::cout << "Output:" << std::endl;
  {
    int np = n / 2 + 1;
    int pos = 0;
#if HORIZONTAL
    for(int j = 0; j < M; ++j) {
      for(int i = 0; i < np; ++i) {
	std::cout << "(" << FX[2 * pos] << "," << FX[2 * pos + 1] << ") ";
	++pos;
      }
      std::cout << std::endl;
    }
#else
    for(int j = 0; j < M; ++j) {
      for(int i = 0; i < np; ++i) {
	std::cout << "(" << FX[2 * pos] << "," << FX[2 * pos + 1] << ") ";
	++pos;
      }
      std::cout << std::endl;
    }
#endif
    std::cout << std::endl;
  }

  clfftTeardown();
  delete[] FX;
  delete[] X;
}

**Comment by bragadeesh** [comment]
Your code has the following mistakes:
1. when you set HORIZONTAL to 0, the ostride value need to be 4. Because, the row width is 4 in your data layout and you are computing transforms along columns.
2. When you are printing the results you need to interchange the i, and j loops 

There are no problems in the library. If you correct these mistakes, you get the following correct output:
(60,0) (64,0) (68,0) (72,0)
(-20,20) (-20,20) (-20,20) (-20,20)
(-20,0) (-20,0) (-20,0) (-20,0)

**Comment by malcolmroberts** [comment]
Thank for the response; that clarifies things for me!  I also have the correct output now; the error was indeed in my call to clFFT.
