### ISSUE TITLE
PackageConfig mishap

### ISSUE THREAD

**Issue by MathiasMagnus** [clMathLibraries/clFFT#106]
Hi!

I'm trying to use the package config file of clFFT (big congrats on providing one), but it seems I'm doing something wrong. Without using FindclFFT.cmake, CMake fails to find the config files, both on Windows and Ubuntu. On Windows I have a registry entry such as:

    PS C:\Users\Matty> Get-ItemProperty -Path HKCU:\SOFTWARE\Kitware\CMake\Packages\
    
    
    clFFT_2.6.1  : C:\Kellekek\AMD\clFFT\2.6.1\CMake
    PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\SOFTWARE\Kitware\CMake\Packages\
    PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\SOFTWARE\Kitware\CMake
    PSChildName  : Packages
    PSDrive      : HKCU
    PSProvider   : Microsoft.PowerShell.Core\Registry

and also on Linux:

    mnagy@opteron:~/Build/clFFT_Test/opteron$ cat ~/.cmake/packages/clFFT_2.6.1.package
    /opt/AMD/clFFT/2.6.1/lib64/cmake/clFFT

but every time I configure a project, I get the following error:

    mnagy@opteron:~/Build/clFFT_Test/opteron$ cmake -D CMAKE_BUILD_TYPE=Release ~/Develop/clFFT_Test/
    -- The C compiler identification is GNU 4.8.2
    -- The CXX compiler identification is GNU 4.8.2
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    CMake Warning at CMakeLists.txt:39 (find_package):
      By not providing "FindclFFT.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "clFFT", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "clFFT" with any of
      the following names:
    
        clFFTConfig.cmake
        clfft-config.cmake
    
      Add the installation prefix of "clFFT" to CMAKE_PREFIX_PATH or set
      "clFFT_DIR" to a directory containing one of the above files.  If "clFFT"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    CMake Warning at CMakeLists.txt:40 (find_package):
      By not providing "FindOpenCL.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "OpenCL", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "OpenCL" with any
      of the following names:
    
        OpenCLConfig.cmake
        opencl-config.cmake
    
      Add the installation prefix of "OpenCL" to CMAKE_PREFIX_PATH or set
      "OpenCL_DIR" to a directory containing one of the above files.  If "OpenCL"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/mnagy/Build/clFFT_Test/opteron

Without providing CMAKE_PREFIX_PATH on the command-line, the paclage config files do not work. What exactly am I doing wrong? According to the CMake wiki

http://www.cmake.org/Wiki/CMake/Tutorials/Package_Registry

it should be working automatically (as is the whole purpose of packages).

**Comment by bragadeesh** [comment]
Closing this old issue; would have to revisit later, after having inputs from @kknox
