### ISSUE TITLE
 clFFT.version.h

### ISSUE THREAD

**Issue by peter73421** [clMathLibraries/clFFT#110]
Dears,

not sure this is an issue: I'm compiling OpenCV with  clMathLibraries/clFFT and getting

    ../opencv/dep/clMathLibraries/clFFT/src/include/clFFT.h:36:27: fatal error: clFFT.version.h: No such file or directory #include "clFFT.version.h" compilation terminated.'

don't see clFFT.version.h 

in clFFT.h you're include it

    36: #include "clFFT.version.h"

**Comment by bragadeesh** [comment]
are you using a binary release package? which version? you can copy that header file from the source repo if you are missing it.

**Comment by peter73421** [comment]
I do not use "binary release" - it might be a problem? I think I need to
use 32bit version for clFTT and since I am building the latest OpenCV 3.0
which uses it - I need to build 32-bit version.
I am not see "clFFT.version.h" @ github source repo. Do I need to compile
the clFFT to get this version file since I see "clFFT.version.h.in
<https://github.com/clMathLibraries/clFFT/blob/develop/src/include/clFFT.version.h.in>
"
Thanks for your comments.

**Comment by bragadeesh** [comment]
Yes, you need to build clFFT and the clFFT.version.h gets generated as part of the build process. If you are not using the binary release, I suppose you have built the library. In that case, that file should be in the include directory of your build folder.

**Comment by peter73421** [comment]
I got it. By building clFFT I need to have "boost" binaries?

**Comment by bragadeesh** [comment]
Yes, please go through the build documentation to get the details on dependencies.
