### ISSUE TITLE
Mention required OpenCL version in README

### ISSUE THREAD

**Issue by flv0** [clMathLibraries/clFFT#111]
The README.md says that any OpenCL SDK is required. I was wondering wether this even includes 1.0, or, if 2.0 might be required. Looking at APP 2.9 it seems OpenCL 1.2 should suffice, but still gives no clue about older versions. I was specifically wondering wether the code will run on NVIDIA hardware, who still refuse to support OpenCL 2.0 and just recently started supporting 1.2 in april this year.

**Comment by flvi0** [comment]
Ok it seems to me that 1.0 won't work since the standard does not define CL_CALLBACK, so narrowed it down to [1.1, 1.2] :) I will see wether I can find a system with a 1.1 runtime to verify.

**Comment by bragadeesh** [comment]
Thanks for the comment, I have update README stating we need 1.2
