### ISSUE TITLE
Multi gpu ffts

### ISSUE THREAD

**Issue by fftfp64** [clMathLibraries/clFFT#125]
Hello.

I hope this is the right forum.

I have a question or three regarding ffts.

1) Is it still true that the clffts cannot be used to farm out
different batches of ffts to separate gpus?

2) If in the above the answer is yes, is there any chance that multi-gpu
clffts will be appearing in the next few months?

3) Is there  cl code that I can copy-n- use/just-study that does batched 1D r2c and c2r 
 ffts in double precision and for factors 2, 3 & 5 and is suitable for the amd gcn? It
now seems as if I will have to write my own ffts for many-gpus. 

Thanks.
--

**Comment by bragadeesh** [comment]
Here are my answers:

q1: Yes, the library cannot do multi-GPU by *itself*. BUT, an application can divide the problem and use multiple GPUs. The sub-problems can be solved with clFFT. People have successfully used clFFT this way in multi-GPU environments. 

q2: Not sure about future plans, we can provide an update when the plans are solid.

q3: You can take a look at the examples or client and also read documentation.
https://github.com/clMathLibraries/clFFT/tree/master/src/examples
https://github.com/clMathLibraries/clFFT/tree/master/src/client
http://clmathlibraries.github.io/clFFT/index.html
http://clmathlibraries.github.io/clFFT/index.html#RealFFT
