### ISSUE TITLE
Segmentation fault on Intel CPU

### ISSUE THREAD

**Issue by rolox** [clMathLibraries/clFFT#129]
I am testing clFFT on my laptop. I  have 2 OpenCl Device / Platforms ( intel and nvidia, more see below).

When I choose the Intel CPU Platform with clFFT as cl device (e.g. with **clFFT-callback-client** or my own software ) as device  I get the following segmentation fault:

**$ clFFT-callback-client -p 1**

**Running FFT for length 1024 and batch size 1**
**Stack dump:**
**0.	Running pass 'Intel OpenCL Vectorizer' on module 'Program'.**
**1.	Running pass 'Intel OpenCL VectorizerCore' on function '@__Vectorized_.fft_fwd'**
**2.	Running pass 'PacketizeFunction' on function '@__Vectorized_.fft_fwd'**
**Segmentation fault (core dumped)**

Can anyone verify this problem?

Regards,
Roland

------ List of devices
num platforms: 2

platform index: 0:
platform id: 0x151c2e0
platform vendor: Intel(R) Corporation
platform name: Intel(R) OpenCL
platform num devices: 1

   device index: 0
   device id: 0x151d3b8
   device type: 2
   global memory size: 15979MB
   local memory size: 32KB
   global cache size: 256KB
   global cacheline size: 64
   max memory alloc size: 3994MB
   max compute units: 8
   max workgroup size: 8192
   max workitem dimensions: 3
   max workitem sizes: 8192 8192 8192
   device name: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
   opencl c version: OpenCL C 1.2 
   opencl device version: OpenCL 1.2 (Build 92)
   frequency MHz: 2400

platform index: 1:
platform id: 0x15285c0
platform vendor: NVIDIA Corporation
platform name: NVIDIA CUDA
platform num devices: 1

   device index: 0
   device id: 0x1528690
   device type: 4
   global memory size: 2047MB
   local memory size: 48KB
   global cache size: 32KB
   global cacheline size: 128
   max memory alloc size: 511MB
   max compute units: 2
   max workgroup size: 1024
   max workitem dimensions: 3
   max workitem sizes: 1024 1024 64
   device name: GeForce GT 740M
   opencl c version: OpenCL C 1.2 
   opencl device version: OpenCL 1.2 CUDA
   frequency MHz: 1032

**Comment by bragadeesh** [comment]
closing this old issue
