### ISSUE TITLE
How to enable binary caching?

### ISSUE THREAD

**Issue by AlexHild** [clMathLibraries/clFFT#144]
I tried to enable binary caching by setting the environment variable CLFFT_CACHE_PATH to "C:\FFTCache\" and other values, but no binaries appeared in that folder.

Is binary caching possible in current versions? If yes, what am I doing wrong?

**Comment by kknox** [comment]
That is not supported in the library at this time; you are looking at disabled code. 

We had the ability to cache kernels before we introduced transpose kernels.  However, since transposes were added, this whole feature doesn't work anymore and is disabled.

**Comment by AlexHild** [comment]
Are there any plans to reactivate binary caching in the nearer future?
Am 22.04.2016 19:13 schrieb "Kent Knox" <notifications@github.com>:

**Comment by kknox** [comment]
I'm sorry, but not in the near future, but this is being tracked in issue #5.

**Comment by AlexHild** [comment]
Is it correct that binary caching was fixed? Just tested it again and it works...

Only found a minor bug (not stoping it from work) in

static char * sep()
{
#ifdef __WIN32
    return (char*)"\\";
#else
    return (char*)"/";
#endif
} 

__WIN32 has one underscore too much leading to wrong paths under windows
