### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by AlexHild** [clMathLibraries/clFFT#146]
Using clFFT from multiple threads I am experiencing different crashes and errors. It feels like out of bounds problems (out of resources or invalid queue errors on GPUs, access violations on CPUs).

Looking through the code for possible thread safety problems I found the following comment in enqueue.cpp:

//	::clSetKernelArg() is not thread safe, according to the openCL spec for the same cl_kernel object
//	TODO:  Need to verify that two different plans (which would get through our lock above) with exactly the same
//	parameters would NOT share the same cl_kernel objects

Debugging my issue I found that there are more plans than kernel objects. As I was only using complex 1D FFTs in this case this means that multiple plans are sharing the same kernel object. 

I guess one solution would be to not only lock plans, but also lock the kernels between the clSetKernelArgs and clEnqueueNDRangeKernel calls.

**Comment by bragadeesh** [comment]
Yes, the multi-threaded scenario needs to be tested well on clFFT. This is lacking as of now. As you have found out, clSetKernelArg is the source of the problem, and if you read the spec, the recommended way is to make separate threads work on separate kernel objects. This way there will not be any contention. We can also use locks, but that will serialize the computation. If the whole point of threading was to run independent jobs in parallel on the gpu, then this approach is not suitable.

**Comment by AlexHild** [comment]
As far as I understand the main thing about thread safety of clSetKernelArg is that it's not safe to change args from different threads before enqueuing. Locking from the first clSetKernelArg to the clEnqueueNDRangeKernel should be enough and should not impact multi threading performance to much.

I tried this with my application and (until now) it seems to fix my issues. Attached you find a patch of my changes.

[patch.zip](https://github.com/clMathLibraries/clFFT/files/274560/patch.zip)

**Comment by bragadeesh** [comment]
Thanks for contributing, I am pulling this in now as-is after basic review; will go into next release after testing ..
