### ISSUE TITLE
clFFT error code 4097 CLFFT_NOTIMPLEMENTED

### ISSUE THREAD

**Issue by juliohm** [clMathLibraries/clFFT#148]
I have an algorithm that is working well with 3D arrays. Today I passed an array with different size (still multiple of 2,3 or 5) and got this strange error. What is the meaning of this error and how to debug it further?

**Comment by juliohm** [comment]
The error has to do with the size of the array. I am calling clFFT via Julia:

```julia
using OpenCL
using CLFFT

A = zeros(168,134,40)

dev, ctx, queue = OpenCL.create_compute_context()

CLFFT.Plan(Complex64, ctx, size(A))
```
>CLFFTError(code=4097, :CLFFT_NOTIMPLEMENTED)

Asserting even dimensions is not enough?

**Comment by AlexHild** [comment]
The dimensions have to be powers of 2,3,5,7,11,13 or any combination of those. In your example 134 does not work because its prime factorization is 2*67.

**Comment by juliohm** [comment]
Thank you @AlexHild! I misread `powers` of 2 by `multiples` of 2 for some reason while reading the docs. I am closing the issue.

**Comment by juliohm** [comment]
Any recommended pre/post processing step to make it work in most cases? I'm
planning to repeatedly pad the array and check for prime factors greater
than 13. If it fails after 2 or 3 iterations, I abort the FFT.

Please let me know if there is a standard way of dealing with arbitrary
shapes.

-Júlio

**Comment by pavanky** [comment]
@juliohm if space is not a concern, always pad to the next power of two. This can be found by some amount of [bit shifting](http://stackoverflow.com/a/466278/2192361).This is the simplest and fastest solution. 

If space is a concern, try a closer number that is has prime factors of 2 and 3. You can use the next power of 2 (say N) to get multiple new candidates by dividing this number:

- by 16 and multiplying by 15 to get a number that is 93% of N.
- by 32 and multiplying by 27 to get a number that is 84% of N.
- by 4 and multiplying by 3 to get a number that is 75% N.
- by 16 and multiplying by 9 to get a number that is 56% of N.

Now that you have 5 numbers, you can find the number that is closest to the original and use that. If you pick correctly, you will probably only lose about 10-20% additional memory from padding.

**Comment by pavanky** [comment]
Just wanted to test how the numbers would look in 2D. Here's what it looks like for a 2D FFT on R9 390x.
```
2048 x 2048:   411 Gflops, 1.1239 ms
1920 x 1920:   130 Gflops, 3.1122 ms
1728 x 1728:   200 Gflops, 1.6389 ms
1536 x 1536:    68 Gflops, 3.8207 ms
1152 x 1152:   156 Gflops, 0.9347 ms
```

**Comment by kknox** [comment]
Thank you @pavanky for the benchmark data and @AlexHild for helping the user

**Comment by juliohm** [comment]
@pavanky that is really helpful! Thank you for putting together such nice tricks, I will experiment them on my code.

**Comment by juliohm** [comment]
@AlexHild can you please comment on the list of supported powers? You mentioned 2,3,5,7,11,13 but I am getting an error message that only lists 2,3,5 as the supported powers. In the documentation the list is 2,3,5,7.

Can someone elaborate on the official list?

**Comment by AlexHild** [comment]
In the release notes (https://github.com/clMathLibraries/clFFT/releases) you can see that starting with 2.12.0 radices 11 and 13 are supported.

**Comment by juliohm** [comment]
What about the radice 7?

-Júlio

**Comment by BenjaminCoquelle** [comment]
Implemented since release 2.8 if you look at the link given by AlexHild before
Most probably the error message hasn't been update since the first release.
But yes the official list is 2,3,5,7,11,13

**Comment by juliohm** [comment]
Thank you all, I'll handle these variations in my package.

-Júlio

**Comment by juliohm** [comment]
Apparently I am on 2.12.0. Perhaps the error message is being shown incorrectly?

**Comment by bragadeesh** [comment]
What API of clFFT is showing the error?

**Comment by juliohm** [comment]
@bragadeesh the error message is from the CLFFT.jl wrapper, I am opening an issue there. Thank you.
