### ISSUE TITLE
Planning FFTs at every function call

### ISSUE THREAD

**Issue by juliohm** [clMathLibraries/clFFT#151]
Could you please elaborate on the machinery behind clFFT plans? I am currently planning the FFT at every call of a function I've wrote for convolving images: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/imfilter_gpu.jl#L35-L39

This function is called multiple times in a big loop and I am wondering how expensive it is to plan the FFT like that. Would I get a sensible speed up by planning the FFT outside and passing the plan as a parameter to the function? Is #5 related?

Thank you.

**Comment by pavanky** [comment]
@juliohm creating plans is quite expensive. We use a fairly simple caching mechanism in arrayfire. You can look at it over here: https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/fft.cpp#L32

**Comment by juliohm** [comment]
@pavanky do you have an estimate of how much time would I save by planning the FFT outside of the function? I am planning to refactor the code if the speedup is considerable.

**Comment by pavanky** [comment]
It depends on the transform size to be honest. What sizes are you working with?

You could simply take the code base from the file I linked to make it easier for you. It's licensed under BSD-3 so it won't be an issue at all.

**Comment by juliohm** [comment]
Thank you @pavanky let's say I am working with grids of size 300x200x50, do you think the plan is relevant compared to the FFT itself? I am gonna check the code you linked to see if I can grasp the caching mechanism. Another unrelated issue that is in my todo list is the complex-to-real transform. I am only interested in scanning grids with real numbers but I couldn't setup the FFT to save memory according to the docs here: http://clmathlibraries.github.io/clFFT/#RealFFT

**Comment by pavanky** [comment]
If you are using 3D FFTs of that size, the overhead should be negligible.

**Comment by kknox** [comment]
Our general recommendation would be to pull the 'planning' step out of any loops; it's the reason we designed the API to have a bake step.  Baking involves generating an OpenCL kernel on the fly and asking the OpenCL runtime to jit-compile/build it.  If it's not too hard to refactor your code, I think you would prefer not to be doing that repeatably inside of a loop if you can easily reuse it.

@pavanky is right; you are running big data so I do not know how much of an overhead it ends up being, but for 1D and 2D FFT's it would be significant.

**Comment by juliohm** [comment]
Thank you all, I will try to refactor the code anyways. In my case I only have two plans (padding vs. non-padding).

Regarding the complex-to-real transform, where in the API can I force it? For instance, where in these lines I specify that I only care about real numbers? https://github.com/juliohm/ImageQuilting.jl/blob/master/src/imfilter_gpu.jl#L35-L39

**Comment by kknox** [comment]
You specify it as the layout call; you want your input buffer to be clfft_real and the output buffer to be hermitian_interleaved for in-place transforms.  The trick is in making sure that you allocate the right amount of memory.  

@bragadeesh do you have any particular advice?

**Comment by bragadeesh** [comment]
You can read http://clmathlibraries.github.io/clFFT/index.html#RealFFT
to understand how to compute real FFTs, important point is the strides and distances need to be set correctly.

2d, 3d real FFTs are not as optimized as their complex counterparts; so if you can help it, I would suggest  sticking to complex FFTs if performance is important

**Comment by juliohm** [comment]
Thank you all, performance is essential to me, I'll stick to complex
transforms then.

Best,
-Júlio
