### ISSUE TITLE
Compile issue on example progs with gcc 5

### ISSUE THREAD

**Issue by darkstar007** [clMathLibraries/clFFT#152]
When I try to compile the examples I get an issue with gcc-5 (version 5.4) on Linux:

`
/tmp/ccgBqE5I.o: In function `main':
test_fft.c:(.text+0x106): undefined reference to `clfftInitSetupData'
collect2: error: ld returned 1 exit status
`

which goes away if I use gcc-4.8 or gcc-4.9.

Thanks

Matt

**Comment by kknox** [comment]
Make sure that you build the library and the example programs with the same compiler.  It is possible that the ABI (application binary interface) changed between the 4.x and the 5.x series.  If you are doing this, I would advise to create separate build directories for each compiler.

**Comment by darkstar007** [comment]
OK - libclfft was installed as part of Debian unstable. I'll check to see how it was compiled.

Thanks,

Matt

**Comment by bragadeesh** [comment]
please reopen if any more questions, closing for now
