### ISSUE TITLE
Segmentation fault on Intel CPUs

### ISSUE THREAD

**Issue by dbeurle** [clMathLibraries/clFFT#155]
See #129 : I am having the same problem with running the example code on Intel Haswell CPU/GPU.  Works fine on a CUDA device.

**Comment by bragadeesh** [comment]
Can you try to debug? It may be a specific HW issue or an issue with version of opencl runtime.
We have partners like Arrayfire successfully running the library on Intel CPUs.

**Comment by bragadeesh** [comment]
@pavanky @shehzan10 any input from you guys would be helpful

**Comment by bragadeesh** [comment]
I am assuming this to be opencl runtime issue; please reopen if reasons to believe this as library issue

**Comment by pavanky** [comment]
@bragadeesh Shehzan is on vacation and I somehow missed this message. I can try out the example and see if it is a problem.

**Comment by shehzan10** [comment]
I remember seeing a similar failure at one point in time (before we went on the bug fix spree).
I can't completely recall what fixed it.

We do not build with callback client on ArrayFire CI. I just tested on an Intel Core i7 4770k and it ran fine.

@dbeurle can you confirm whether you are on the latest OpenCL runtime? Also what is the CPU/GPU model number that you are using?

**Comment by dbeurle** [comment]
I think this was a bad OpenCL runtime implementation.  I use the Intel and the nvidia ones without a problem.
