### ISSUE TITLE
Large memory leaks when running the testsuite

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clFFT#156]
Upon running the testsuite on `v2.12.1`, I noticed a sharp rise in memory consumption that never gets released when the test finishes. Memory consumption keeps rising until the max is achieved, then the rest of the testsuite keeps reporting exceptions about lack of memory available on the host. When the testsuite eventually finishes, this memory does not get released hence forcing a reboot.

Is this behavior observed by other people?

**Comment by bragadeesh** [comment]
In our testing on Linux with AMD GPUs, we did not notice this problem. Can you give details on the machine & OS & driver that you are using?

**Comment by ghisvail** [comment]
It is a Thinkpad T440 with an Nvidia GeForce 730M. I am running Debian testing with the nvidia driver 352.79. It was also failing on our builder machine which runs on an Intel(R) Xeon(R) CPU E5-2697 v3 with the latest release of pocl (version 0.13).

**Comment by ghisvail** [comment]
From my observations, whilst running the testsuite with the `--short` argument, the first part of the testsuite runs fine. It is around when the inplace / out-of-place tests begin that the memory consumption starts to rise.

**Comment by bragadeesh** [comment]
I tested the following setups: Linux + AMD OpenCL + AMD GPU; Windows + AMD OpenCL + AMD GPU; and Windows + Intel OpenCL + Intel CPU. In all 3 cases, the memory usage remained contained as successive tests ran and finished. As expected, the usage went up when running a test and then shrunk back when the test finished and so on through the end. The inplace/out-of-place tests ran fine. I cannot see any symptom of major leaks. I don't believe this is a library issue. It is probably an issue with the stack on your side. I am closing this now, please reopen if you can point out library leak specifically.

**Comment by ghisvail** [comment]
Is that supposed to happen then:

Constant rise of RAM consumption starting when `accuracy_test_pow2_precallback` is launched:
![screenshot from 2016-08-09 15-48-14](https://cloud.githubusercontent.com/assets/1964655/17521277/ac673a8a-5e4a-11e6-9196-54cf522736e7.png)

Memory consumption hits the maxmum allowed by the host, the testsuite fails to execute the remaining tests as a result:
![screenshot from 2016-08-09 15-49-11](https://cloud.githubusercontent.com/assets/1964655/17521275/aae8ef28-5e4a-11e6-9dbf-695f90ce5b19.png)

The testsuite is killed manually to clear the memory.
![screenshot from 2016-08-09 15-49-38](https://cloud.githubusercontent.com/assets/1964655/17521273/a972ad32-5e4a-11e6-8074-4ec2d0e5a865.png)

**Comment by ghisvail** [comment]
> I tested the following setups: Linux + AMD OpenCL + AMD GPU; Windows + AMD OpenCL + AMD GPU; and Windows + Intel OpenCL + Intel CPU

So no nvidia ?

> the memory usage remained contained as successive tests ran and finished.

Please define "remained contained", because here this is 10 GB of RAM being used and rising.

> As expected, the usage went up when running a test and then shrunk back when the test finished and so on through the end.

This is what I observed for `accuracy_test_pow2`. These graphs tell me this is not what is happening in `accuracy_test_pow2_precallback`.

> I don't believe this is a library issue. It is probably an issue with the stack on your side.

Please elaborate what you define by "issue with the stack" here. Where could the massive memory consumption come from then ?

Thanks,
Ghis

**Comment by bragadeesh** [comment]
What I meant by contained is that the memory consumption was in the tens of MBs before a test starts to run and then depending on the test (with the associated problem size) the consumption would rise to hundreds of MBs and then after the test finishes, the consumption would fall back to the tens of MBs. It never touched GBs, for the named enabled tests, including the callback tests and *4M* tests.

I am suspecting the 'huge' local memory size provided by POCL may be causing these issues. Please see my comments in the open issue tracker #161 .

**Comment by ghisvail** [comment]
To make sure we are on the same page here, the graphs shown here are for an execution on nvidia hardware, not pocl.

**Comment by ghisvail** [comment]
The workstation here runs a `Tesla K40c`. I get the same behaviour on my `GeForce GT 730M`.

**Comment by bragadeesh** [comment]
Hmmm, ok. Nevertheless, could you try the code change I posted in #161 ? It tricks the library to run under CL parameters as available on an AMD GPU, as the libraries were designed for that originally. Since the CL limits on NV runtime and POCL are bigger, this 'hack' is worth a shot to try and see if it fixes these issues.

**Comment by ghisvail** [comment]
I applied the following patch:
```
diff --git a/src/library/plan.cpp b/src/library/plan.cpp
index 19e50dc..bcc03da 100644
--- a/src/library/plan.cpp
+++ b/src/library/plan.cpp
@@ -4735,7 +4735,12 @@ clfftStatus FFTPlan::SetEnvelope ()
                                envelope.limit_Size[u] = std::min<size_t> (envelope.limit_Size[u], temp[u]);
                        }
                }
-
+               envelope.limit_LocalMemSize = 32768;
+               envelope.limit_Dimensions = 3;
+               envelope.limit_WorkGroupSize = 256;
+               envelope.limit_Size[0] = 256;
+               envelope.limit_Size[1] = 256;
+               envelope.limit_Size[2] = 256;
                BUG_CHECK (envelope.limit_LocalMemSize >= 1024)
        } while (0);

```
And I get a similar outcome on the workstation with the `Tesla K40c`. Shall I still try on my laptop with `pocl` ?

**Comment by bragadeesh** [comment]
Hmmm. Yes, could you try with pocl on CPU.
On NV, can you post the 'clinfo' output.
