### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by arkosabui** [clMathLibraries/clFFT#164]
Not an issue but I wanted a fast response to this query so adding as an issue. Please don'e report me.
 Q: Does an Android port of this library exist? Has anyone tried it? If so, can someone please point me (with a hyperlink) to the right resources?

**Comment by bragadeesh** [comment]
I am not aware of any Android ports. Would be interesting to know if anyone tried to make that work ..

**Comment by pavanky** [comment]
Android port will be particularly hard given the hostile nature Google has towards OpenCL.
