### ISSUE TITLE
NVIDIA clLenghts error

### ISSUE THREAD

**Issue by Anastas-Ruskov** [clMathLibraries/clFFT#166]
I have a problem while trying 1D fft with 16 384 size, clfftBakePlan function returns -42 error(CLFFT_INVALID_BINARY). My Nvidia is NVIDIA GeForce GT 220. I tried the same code on AMD video card and there were no problems.
Any solution?
Thanks in advance!

**Comment by bragadeesh** [comment]
Not all cards are supported, this is probably vendor openCL support issue.
