### ISSUE TITLE
gcc -std=c11 --> undefined ref to clfftInitSetupData

### ISSUE THREAD

**Issue by fftfp64** [clMathLibraries/clFFT#169]
Hello.

I have been using clfft on Ubuntu 14.04  for a year now and it works fine. The c/cl routines were compiled with gcc (the main prog is fortran with c interfacing opencl.) I am now trying to use
aligned_alloc which  requires the c11 version. When I add the -std=c11 option to the gcc command
line it compiles ok but on linking the fortran and c  .o files with ifort (intel) it complains that it
can no longer find 'clfftInitSetupData'. I've tried clfft 2.6.1 and 2.12.2 precompiled binaries.
Is it possible to say what is going on?

**Comment by bragadeesh** [comment]
Pre-built binaries are not helping. You would have to rebuild the library again with the c11 option and try. Mixing compilers is not easy, you would have to do some trial & error; unfortunately we are unable to help further.
