### ISSUE TITLE
hermitian interleaved to real fails on 4096 (CPU)

### ISSUE THREAD

**Issue by tdd11235813** [clMathLibraries/clFFT#171]
Hi,
I get an error for 4096 and for 4096x4096 when running backward transform (hermitian interleaved -> real):
```
clFFT-client -x 4096 -p 2 --inLayout 3 --outLayout 5
clFFT-client -x 4096 -y 4096 -p 2 --inLayout 3 --outLayout 5
```
The error is:
```
clFFT error condition reported:
OPENCL_V_THROWERROR< CLFFT_OUT_OF_RESOURCES > (507): clfftEnqueueTransform failed
```
It works fine with forward transform (real -> hermitian interleaved) and other sizes like 2048 or 8192.

Tested on clfft 2.12.2, and with latest dev branch. I am working on RHEL6.7 with boost/1.60.0-gnu5.3-intelmpi5.1 opencl/1.2-4.4.0.117 cuda/8.0.44 gcc/5.3.0.

Can you reproduce it on your side?

Best Regards
Edit: affects Inplace and Outplace, single precision

**Comment by tdd11235813** [comment]
On a GPU (K80) the error does not occur, but only on the CPU:
```
CL_DEVICE_NAME:                  Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
CL_DEVICE_VERSION:               OpenCL 1.2 (Build 44)
CL_DRIVER_VERSION:               1.2.0.44
```

**Comment by bragadeesh** [comment]
I can confirm that I can reproduce this on my side. But CPU is low priority and we don't have sufficient resources to investigate this.

**Comment by bragadeesh** [comment]
I wish there was a 'back-burner/shelved' state to issues rather than just open & closed. Anyway, I am closing this for now, noted this issue in our internal list.
