### ISSUE TITLE
float test error

### ISSUE THREAD

**Issue by neil1899** [clMathLibraries/clFFT#173]
hi, all

i have porting clfft fftw3 on qualcomm paltform,  when i run the Test, float test is failed.

[ RUN      ] accuracy_test_pow2_single.single_point_1D_forward_complex_to_complex
Floating point exception

but example test fft1d/ 2d/ 3d is ok

what's the reason might be? 

thanks in advance!

**Comment by bragadeesh** [comment]
You would have to debug on your own; not familiar with this hardware unfortunately we are unable to help.
