### ISSUE TITLE
kernel compilation errors

### ISSUE THREAD

**Issue by bexizuo** [clMathLibraries/clFFT#177]
Hi all, 
i'm having issue on ARM MALI (Odroid-XU3 board),
i would like to use example fft1d ... i setup size 512 ... everything running without error ... i'm attaching kernel program, 
but when i setup size 1024 in fft1d.c in examples i'm getting this error message: 

> 			BUILD LOG
>************************************************
><source>:1580:19: error: initializing '__global float4 *' with an expression of incompatible type >'__global float2 *'
>        __global float4 *buff4g = bufOut;
>                         ^        ~~~~~~
>
><source>:2003:19: error: initializing '__global float4 *' with an expression of incompatible type >'__global float2 *'
>        __global float4 *buff4g = bufOut;
>                         ^        ~~~~~~
>
><source>:2016:49: warning: unknown attribute 'max_constant_size' ignored
>void fft_fwd(__constant cb_t *cb __attribute__((max_constant_size(32))), __global float2 * restrict gb)
>                                                ^
>
><source>:2042:50: warning: unknown attribute 'max_constant_size' ignored
>void fft_back(__constant cb_t *cb __attribute__((max_constant_size(32))), __global float2 * restrict >gb)
>                                                 ^
>
>error: Compiler frontend failed (error code 59)
>
>************************************************
>FFTGeneratedStockhamAction::compileKernels failed

i'm also attaching that error msg 
[fft1d_error_kernel_N1024.txt](https://github.com/clMathLibraries/clFFT/files/722856/fft1d_error_kernel_N1024.txt)
and kernel program related to that error ... 
[clfft_kernel_N512.txt](https://github.com/clMathLibraries/clFFT/files/722823/clfft_kernel_N512.txt)
[clfft_kernel_N1024.txt](https://github.com/clMathLibraries/clFFT/files/722824/clfft_kernel_N1024.txt)

**Comment by bragadeesh** [comment]
You could try to cast the float2 pointer to float4 explicitly to see if the compiler will allow that. At Line 822 in https://github.com/clMathLibraries/clFFT/blob/develop/src/library/generator.stockham.cpp is where that kernel code is generated. Maybe you can modify that and rebuild library to see if any success.

**Comment by bexizuo** [comment]
Hi bragadeesh, 
this tricky approach works for me ... maybe it could be useful if it will be there by default ... :-) 

but i have another question: i compared results from size N=  4*1024*1024; and i see big differences: 
> ==> tmp_output_clFFT_N4M.txt <==
> 0 (8796090925056, 26388272775168)
> 1 (-8399651602432, 2799877226496)
> 2 (-4199827374080, 1399935467520)
> 3 (-2799885615104, 933288083456)
> 4 (-2099914473472, 699964588032)
> 5 (-1679932260352, 559970385920)
> 6 (-1399943856128, 466640896000)
> 7 (-1199951839232, 399977086976)
> 8 (-1049958285312, 349979148288)
> 9 (-933296340992, 311091855360)
> 
> ==> tmp_output_fftw3_N4M.txt <==
> 0 (8796090925056, 26388272775168)
> 1 (-8399652126720, 2799876964352)
> 2 (-4199827111936, 1399935336448)
> 3 (-2799885352960, 933288148992)
> 4 (-2099914604544, 699964522496)
> 5 (-1679932129280, 559970385920)
> 6 (-1399943725056, 466640928768)
> 7 (-1199952101376, 399977054208)
> 8 (-1049958350848, 349979115520)
> 9 (-933296537600, 311091855360)

is it normal ? only index zero match :-( 
thanks in advance ...

**Comment by tingxingdong** [comment]
what is the print out? It is the numerical results? It is in float?  if it is float, then only the first 6-7 digits are significant, the remaining digits are garbage.  
https://en.wikipedia.org/wiki/Single-precision_floating-point_format

**Comment by bexizuo** [comment]
this was command to printout results: 
printf("%d (%.0f, %.0f)\n", print_iter, roundf(X[2 * print_iter]), roundf(X[2 * print_iter+1]));
... still from example fft1d.c

well ... ok ... thank you ... :-) 
kind regards ...

**Comment by kknox** [comment]
@bexizuo 
There is not an efficient method to force the GPU to compute the same exact results as the CPU.  The GPU is data parallel and will execute floating point arithmetic in a different order.  The common saying is that [floating point arithmetic is not associative](http://cass-mt.pnnl.gov/docs/pubs/pnnleffects_of_floating-pointpaper.pdf).  Your output looks to have a high magnitude, and makes me think that there is plenty of runway for floating point rounding error to accumulate.

**Comment by bexizuo** [comment]
@kknox , thank you for information ... so my issue was regarding kernel code error ... now i have it solved by type casting ... thank you ... and i think if you commit it then it could good for those who are use it from distro's bin ...

**Comment by kknox** [comment]
@bexizuo 
If you make a PR targeting the /develop branch, i'm sure that @bragadeesh would be happy to review and merge it for you.
