### ISSUE TITLE
initial values of output buffer change results

### ISSUE THREAD

**Issue by jheek** [clMathLibraries/clFFT#180]
I observe the following unexpected behavior when performing a real -> hermitian interleaved forward transformation. I created the following plan:
`
clfftPlanHandle fftPlan;
    size_t xDims[] = {16, 16};
    
    clfftCreateDefaultPlan(&fftPlan, model->context->context, CLFFT_2D, xDims);
    
    int err;
    
    err = clfftSetPlanPrecision(fftPlan, CLFFT_SINGLE);
    err = clfftSetLayout(fftPlan, CLFFT_REAL, CLFFT_HERMITIAN_INTERLEAVED);
    err = clfftSetResultLocation(fftPlan, CLFFT_OUTOFPLACE);
    clfftSetPlanBatchSize(fftPlan, 1);
    clfftBakePlan(fftPlan, 1, &model->context->queue, NULL, NULL);`

The provided diff shows the different results for either initializing all values of the output buffer with NaNs or zeros. 
https://www.diffchecker.com/72esSMf2

**Comment by pavanky** [comment]
You should also include how you are using the plan.

**Comment by jheek** [comment]
Turns out I have to explicitly set the plan distance and strides when using hermitian interleaved plan. Although I get why this is the case I think it would be nice to mention that the default values are most likely invalid for a hermitian interleaved layout.

**Comment by NPellet** [comment]
I also just encountered this problem and indeed for me as well, setting the stride and dimension in the interleaved plan worked out.

However, this should really be documented somewhere. I also expected the default values to follow, especially when no call to setStride or setDimension is made in the preparation of the plan.
