### ISSUE TITLE
Another macOS Sierra Issue

### ISSUE THREAD

**Issue by amcelroy** [clMathLibraries/clFFT#183]
Having some trouble running the FFT in OSX. It works fine on all 3 OpenCL devices on the Windows side, but none of the devices on the OS X side. 

I compiled the macOS debug .dylib code in CMake using the instructions and copy this to my project directory, a Mono project interfaced used Cloo. Things run fine until the clfftBakePlan call. The code is crashing in the **getSingleBinaryFromProgram** function, specifically the line **    cl_int err = clGetProgramInfo(program, CL_PROGRAM_BINARY_SIZES,
                                  sizeof(size_t),
                                  &size, NULL);**

I am pretty new to macOS but would be willing to help fix the issue if anyone has any suggestions.

Again, this code works fine using Mono, Cloo, and the clFFT.dll (also built from source).

Outstanding library by the way, it has really come a long way and we use it a bunch in our Biomedical Imaging lab at UT!

**Comment by bragadeesh** [comment]
Thanks for the compliments!

Unfortunately macOS is currently not in our support matrix; but in the past we had tried to make it work with success. There were other community users who were able to use it successfully. It would be nice if any of them chimed in.

If you have to debug this yourself, I would first try to see if the underlying OpenCL API functions are working in a separate stand-alone program. In this case you would have to construct your own program and play with the clGetProgramInfo API. Once you figure that out, perhaps lessons learned could help you go forward with the library. If the opencl part works fine, then you can see if the parameters passed into the api in the library code is valid or not.

**Comment by amcelroy** [comment]
Also, it has already been reported, sorry for the double posting of an issue.

https://github.com/clMathLibraries/clFFT/issues/83
