### ISSUE TITLE
clFFT Cmake not able to find OpenCL_INCLUDE_DIRS

### ISSUE THREAD

**Issue by saviogeorge** [clMathLibraries/clFFT#186]
Hello I tried to build the clFFT library from the sources however I encountered a Problem as shown in the attached snapshot  "clfft_cmake"

I tried to set the path env but still Cmake could not identify the opencl includes.

I have installed a opencl1.2 Version which Comes as a package with the Intel Media Server Studio.

Kindly let me know a Workaround.

![env_set](https://cloud.githubusercontent.com/assets/20711873/24747100/a02a10d4-1abb-11e7-8431-57c425771f99.png)

![clfft_cmake](https://cloud.githubusercontent.com/assets/20711873/24747041/5c3e0f92-1abb-11e7-95f4-30e65a65d90d.png)

**Comment by bragadeesh** [comment]
Its a cmake thing that you need to figure out on your platform, try searching online/forums; this is not library related.
