### ISSUE TITLE
issue with 8k FFT 1D on intel graphics

### ISSUE THREAD

**Issue by bexizuo** [clMathLibraries/clFFT#187]
Hi guys, 

please could you help me ? 
i'm trying to run clFFT current version on intel i5-4250U , 
intel graphics HD 5000, OpenCL 1.2, 
linux kernel 4.9.13 64bit

i tried to run 4k FFT 1D (for examples) and everything went smoothly, but i tried to run 8k FFT 1D and i got error: 
> OPENCL_V< CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST > (659): clEnqueueNDRangeKernel failed
> OPENCL_V< CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST > (556): clfftEnqueueTransform large1D second column failed

i'm attaching kernel programs for 4k and for 8k ... 
size of 4k FFT kernel code is 453712Bytes
size of 8k FFT kernel code is 30735Bytes ... isn't it too small ? 

[clfft_tmp_program_kernel_4kB.txt](https://github.com/clMathLibraries/clFFT/files/908128/clfft_tmp_program_kernel_4kB.txt)
[clfft_tmp_program_kernel_8kB.txt](https://github.com/clMathLibraries/clFFT/files/908129/clfft_tmp_program_kernel_8kB.txt)

**Comment by bragadeesh** [comment]
The 8K is a 2-kernel solution so the size of kernels should not be thought of as an issue. You would have to debug why this is not working by inspecting the clinfo output for the card you are using and if there are any limitations associated with that. Does running on the CPU work?

**Comment by bexizuo** [comment]
Hello, 
i'm sorry but i don't really understand your question ... 
i'm able to run clFFT as it is on ARM platform on Mali GPU without any issue, 
it seem to be an issue of Intel platform ... 

currently i'm waiting for status of this issue i submitted as bug to beignet 
https://bugs.freedesktop.org/show_bug.cgi?id=100639

**Comment by tingxingdong** [comment]
It looks like a runtime error.  The openCL runtime is provided by vendor (here, Intel).

**Comment by bexizuo** [comment]
Hi guys, 

i found that there was buggy beignet (OpenCL runtime) for Haswell during some period, and that version was commited to debian's stable release jessie , meanwhile bug was fixed in beignet but wasn't commited to jessie during my investigation about performance ... so i used version from git and it's running correctly ... i also checked correctness of results ... 

sorry for bothering ...

**Comment by tingxingdong** [comment]
thank you for doing that
