### ISSUE TITLE
about clfft computation speed

### ISSUE THREAD

**Issue by UsherWang** [clMathLibraries/clFFT#189]
Hi there, 

I was testing clfft on NVIDIA gtx690 single card these days because I want to rewrite my CUDA 
 version code into OpenCL for it supports much more platforms. My results came out to be that clfft performs quite a bit slower than cufft. I didn't expect such difference in performance so I'm wondering maybe I made mistakes somewhere.

The test is for 3D out-of-place fft forward-inverse transform for clfft and cufft in both single and double precision. The test is done with fft size to be N^3 which N varies from 16 to 200 with step 1. The entire code is almost the same as the 1D example on clfft website with some small changes such as more temporary device memory for out-of-place transforms and changed INPLACE to OUTOFPLACE.

I recorded the time for each size of execution(the time for dimension which is not a combination of 2,3,5,7 is changed into the smallest available size larger than it.), and found that, generally speaking, the computation time for clfft is averagely 4 to 5 times slower than cufft. The largest difference even reached 10 times or even larger... Btw, the output are correct, which means the ffts are correctly implemented for both clfft and cufft. Is there anything undone for better computation speed of clfft? I will leave my OpenCL code below. Thank you guys very much for helping me with this issue.

`double Cpyf(float *ip, int len_x, int len_y, int len_z, int iter_num, 
			float *error)
{
	cl_int err;
    cl_platform_id platform[5];
    cl_device_id device[5];
    cl_context_properties props[3] = { CL_CONTEXT_PLATFORM, 0, 0 };
    cl_context ctx = 0;
    cl_command_queue queue = 0;
    cl_mem bufX, buf_tmp, buf_out;

	int pf_id, dev_id;
	pf_id = 0;
	dev_id = 3;

	//float *X;
    cl_event event = NULL;
	size_t N = len_x*len_y*len_z;

	float *input = new float[N*2];
	for (int tmp = 0; tmp < N; tmp++)
	{
		input[tmp*2] = ip[tmp];
		input[tmp*2+1] = 0;
	}

	/* FFT library realted declarations */
	clfftPlanHandle planHandle;
	clfftDim dim = CLFFT_3D;
	size_t clLengths[3] = {len_x,len_y,len_z};

    /* Setup OpenCL environment. */
    err = clGetPlatformIDs( 5, platform, NULL );
    err = clGetDeviceIDs( platform[pf_id], CL_DEVICE_TYPE_GPU, 5, device, NULL );

    props[1] = (cl_context_properties)platform[pf_id];
    ctx = clCreateContext( props, 1, &(device[dev_id]), NULL, NULL, &err );
    queue = clCreateCommandQueue( ctx, device[dev_id], 0, &err );

    /* Setup clFFT. */
	clfftSetupData fftSetup;
	err = clfftInitSetupData(&fftSetup);
	err = clfftSetup(&fftSetup);

    /* Prepare OpenCL memory objects and place data inside them. */
    bufX = clCreateBuffer( ctx, CL_MEM_READ_ONLY, 2 * N * sizeof(float), 
		NULL, &err);
	buf_tmp = clCreateBuffer( ctx, CL_MEM_READ_WRITE, 2 * N * sizeof(float), 
		NULL, &err);
	buf_out = clCreateBuffer( ctx, CL_MEM_WRITE_ONLY, 2 * N * sizeof(float), 
		NULL, &err);

    err = clEnqueueWriteBuffer( queue, bufX, CL_TRUE, 0, 2 * N * sizeof(float), 
		input, 0, NULL, NULL );
	err = clFinish(queue);

	/* Create a default plan for a complex FFT. */
	err = clfftCreateDefaultPlan(&planHandle, ctx, dim, clLengths);

	/* Set plan parameters. */
	err = clfftSetPlanPrecision(planHandle, CLFFT_SINGLE_FAST);
	err = clfftSetLayout(planHandle, CLFFT_COMPLEX_INTERLEAVED  , 
		CLFFT_COMPLEX_INTERLEAVED);
	err = clfftSetResultLocation(planHandle, CLFFT_OUTOFPLACE);

    /* Bake the plan. */
	err = clfftBakePlan(planHandle, 1, &queue, NULL, NULL);
	err = clFinish(queue);

	size_t fft_tmp_buf_size;
	err = clfftGetTmpBufSize(planHandle, &fft_tmp_buf_size);
	cl_mem fft_tmp_buf;
	fft_tmp_buf = clCreateBuffer( ctx, CL_MEM_READ_WRITE, fft_tmp_buf_size, 
		NULL, &err);
	err = clFinish(queue);

	/* Execute the plan. */
	clock_t start,end;
	start = clock();  
	for (int tmp = 0; tmp < iter_num; tmp ++)
	{
		err = clfftEnqueueTransform(planHandle, CLFFT_FORWARD, 1, 
			&queue, 0, NULL, NULL, &bufX, &buf_tmp, fft_tmp_buf);
		err = clfftEnqueueTransform(planHandle, CLFFT_BACKWARD, 1, 
			&queue, 0, NULL, NULL, &buf_tmp, &buf_out, fft_tmp_buf);
	}
	
	/* Wait for calculations to be finished. */
	err = clFinish(queue);
	end = clock();  
	printf("OpenCL Single Precision time=%f\n",(double)(end-start)/CLK_TCK);

	/* Fetch results of calculations. */
	float *output = new float[2*N];

	/*
	err = clEnqueueReadBuffer( queue, buf_out, CL_TRUE, 0, 2 * N * sizeof(float), 
		output, 0, NULL, NULL );
	*/
	err = clEnqueueReadBuffer( queue, buf_out, CL_TRUE, 0, 2 * N * sizeof(float), 
		output, 0, NULL, NULL );

    /* Release OpenCL memory objects. */
    clReleaseMemObject( bufX );
	clReleaseMemObject( buf_tmp );
	clReleaseMemObject( buf_out );
	clReleaseMemObject( fft_tmp_buf );

	/* Release the plan. */
	err = clfftDestroyPlan( &planHandle );

    /* Release clFFT library. */
    clfftTeardown( );

    /* Release OpenCL working objects. */
    clReleaseCommandQueue( queue );
    clReleaseContext( ctx );

	float residue = 0;
	for (int tmp = 0; tmp < N; tmp++)
	{
		residue = residue + (input[2*tmp]-output[2*tmp])*
			(input[2*tmp]-output[2*tmp])+(input[2*tmp+1]-output[2*tmp+1])*
			(input[2*tmp+1]-output[2*tmp+1]);
	}
	std::cout<<residue/N<<std::endl;
	*error = residue/N;

	free(output);
	free(input);

	return (double)(end-start)/CLK_TCK;
}
`

**Comment by tingxingdong** [comment]
Hi, That is not surprising. A lot of  OpenCL code running very well on AMD turns out to be very slow on Nvidia card. It it the Nvidia's OpenCL problem. Nvidia only optimize for CUDA runtime stack .

**Comment by bragadeesh** [comment]
@UsherWang although what @tingxingdong said is generally true, we have not focused on 3d fft optimizations, except on a case-by-case basis;
there is still lot of room for improvement even algorithm-wise for 3d

**Comment by UsherWang** [comment]
I see. Thank you guys very much for helping me with it!
