### ISSUE TITLE
Help with clFFT - Different Results

### ISSUE THREAD

**Issue by ghostop14** [clMathLibraries/clFFT#190]
I"m struggling through an issue with clFFT I was hoping someone could
help with.  Quick background before the code snippits....

I have complex interleaved input data going into a 1D forward
transform.  I also have a known good CPU implementation of an FFT
transform.  When I look at the output from the clFFT version and
compare it to the known good, the results don't match.

I know, "don't match" is subjective so here's what I see.  I take each
result (known good and clfft output) out to 12 decimal places and look at the difference.  Every
point varies past the 4th decimal and the very last data point has a
significant difference.

I've followed the example code on the github page, I believe "to the
letter".  I must be missing something obvious in the plan setup.  Here's the
framework for the setup (the device,context and queue are set up from
the C++ classes and kept around in the class.  The necessary c-style
handles are returned with the () operators for the function calls
below) [I do actually check the err returns I just removed it for
brevity.  None are failing.:

        clfftSetupData fftSetup;
        err = clfftInitSetupData(&fftSetup);
        err = clfftSetup(&fftSetup);
        size_t clLengths[1] = {(size_t)2048};
        err = clfftCreateDefaultPlan(&planHandle, (*context)(),CLFFT_1D, clLengths);
            err = clfftSetPlanPrecision(planHandle, CLFFT_SINGLE);
           err = clfftSetLayout(planHandle, CLFFT_COMPLEX_INTERLEAVED,CLFFT_COMPLEX_INTERLEAVED);
           clfftSetPlanScale(planHandle, CLFFT_FORWARD, 1.0f); 
          clfftSetPlanScale(planHandle, CLFFT_BACKWARD, 1.0f);
        err = clfftSetResultLocation(planHandle, CLFFT_OUTOFPLACE);
        err = clfftBakePlan(planHandle, 1, &(*queue)(), NULL, NULL);

---------------------------------------------------
Input is a std::complex[2048] array copied into the queued buffer and
a std::complex[2048] array used when the data is copied out.

    	err = clfftEnqueueTransform(planHandle, fftDir, 1, &((*queue)()), 0, NULL, NULL, &((*aBuffer)()), &((*cBuffer)()), NULL);
        err = clFinish((*queue)());

I'm assuming I missed something setting up the plan but for the life
of me I don't see what.  Any help would be greatly appreciated!  (FYI,
it's running on debian with libclfft version 2.12.2.  I also tried it
on an Ubuntu 16.04 LTS box with the same results.  The OpenCL device is an
NVIDIA GTX 1070).

**Comment by tingxingdong** [comment]
read  this first to understand the significant digits in float precsion.
https://en.wikipedia.org/wiki/Single-precision_floating-point_format

Every point varies past the 4th decimal and the very last data point has a
significant difference. Can you give an example?

**Comment by ghostop14** [comment]
Sure and thanks for replying.  I've actually been doing a good bit of signal processing work with OpenCL.  My full implementation for my modules actually even detects if the card supports double precision and adjusts accordingly.

Here's the test code I have.  If you switch the planprecision to CLFFT_DOUBLE in the setup, the copy float->double in the test case makes more sense (this is for gnuradio which passes arrays of floats so I have to convert):

    int clFFT_impl::FFTValidationTest(bool fwdXForm) {
    	int l_fft_size = d_fft_size;

    	gr_complex input_items[l_fft_size];
    	gr_complex output_items_gnuradio[l_fft_size];
    	gr_complex output_items_opencl[l_fft_size];

    	int i;

    	// Create some data
    	float frequency_signal = 10;
    	float frequency_sampling = l_fft_size*frequency_signal;
    	float curPhase = 0.0;
    	float signal_ang_rate = 2*M_PI*frequency_signal / frequency_sampling;

    	for (i=0;i<l_fft_size;i++) {
			input_items[i] = gr_complex(sin(curPhase+(signal_ang_rate*i)),cos(curPhase+(signal_ang_rate*i)));
			output_items_gnuradio[i] = gr_complex(0.0,0.0);
			output_items_opencl[i] = gr_complex(0.0,0.0);
    	}


        const gr_complex *in = (const gr_complex *) &input_items[0];
        gr_complex *out = (gr_complex *) &output_items_gnuradio[0];

		std::cout << "Running native transform..." << std::endl;
        // Run an FFT with GNURadio code
		memcpy(d_fft->get_inbuf(), in, l_fft_size*sizeof(gr_complex));
		d_fft->execute();
		memcpy (out, d_fft->get_outbuf (), l_fft_size*sizeof(gr_complex));

        // Run an FFT with OpenCL code
		out = (gr_complex *) &output_items_opencl[0];

		// Move float->double for transform
		DComplex tmpDoubleComplex[l_fft_size];
		for (int j=0;j<l_fft_size;j++) {
			tmpDoubleComplex[j].real = (double)in[j].real();
			tmpDoubleComplex[j].imag = (double)in[j].imag();
		}
    	// Note: inputSize is set in setBufferLength().  inputSize = fft_size * sizeof(data type)
        queue->enqueueWriteBuffer(*aBuffer,CL_TRUE,0,l_fft_size*sizeof(DComplex),(void *)&tmpDoubleComplex[0]);

		std::cout << "Running OpenCL transform..." << std::endl;

        int err;
    	err = clfftEnqueueTransform(planHandle, fftDir, 1, &((*queue)()), 0, NULL, NULL, &((*aBuffer)()), &((*cBuffer)()), NULL);
        if( err != CL_SUCCESS ){
        	std::cout << "OpenCL FFT Error enqueuing transform.  Error code " << err << std::endl;
        	exit(1);
        }
        // Wait for calculations to be finished.
        err = clFinish((*queue)());
        if( err != CL_SUCCESS ){
        	std::cout << "OpenCL FFT Error finishing transform.  Error code " << err << std::endl;
        	exit(1);
        }
        // Fetch results of calculations.
    	queue->enqueueReadBuffer(*cBuffer,CL_TRUE,0,l_fft_size*sizeof(DComplex),(void *)&tmpDoubleComplex[0]);
		for (int j=0;j<d_fft_size;j++) {
			out[j].real((float)tmpDoubleComplex[j].real);
			out[j].imag((float)tmpDoubleComplex[j].imag);
		}

        // Compare results

		float o_r_gnuradio,o_i_gnuradio,o_r_opencl,o_i_opencl;
		float diff_real,diff_imag;

		std::cout << "Comparing transform results..." << std::endl;
		bool resmatched=true;
		int numMismatched = 0;

		for(i=0;i<l_fft_size;i++) {
			o_r_gnuradio = round(output_items_gnuradio[i].real(),12);
			o_i_gnuradio = round(output_items_gnuradio[i].imag(),12);
			o_r_opencl = round(output_items_opencl[i].real(),12);
			o_r_opencl = round(output_items_opencl[i].imag(),12);

			diff_real = fabs(o_r_gnuradio - o_r_opencl);
			diff_imag = fabs(o_i_gnuradio - o_i_opencl);

			if (diff_real > 0.0 || diff_imag > 0.0) {
				resmatched = false;
				std::cout << std::fixed << std::setw(12)
			    << std::setprecision(12) << "Output varied for sample " << i << ": real diff=" << diff_real << " imag diff=" << diff_imag << std::endl;
				numMismatched++;
			}
		}

		if (resmatched) {
			std::cout << "Results matched." << std::endl;
		}
		else {
			std::cout << numMismatched << " out of " << l_fft_size << " didn't match." << std::endl;

		}
    }

    float clFFT_impl::round(float input, int precision) {
    	float num = input*pow(10.0,(float)precision);
    	long part = (long)num;

    	return ((float)part)/pow(10.0,(float)precision);
    }

**Comment by ghostop14** [comment]
Here's the tail end of the test run:

Output varied for sample 2040: real diff=0.000009568400 imag diff=0.000009840500
Output varied for sample 2041: real diff=0.000005638100 imag diff=0.000006594900
Output varied for sample 2042: real diff=0.000011384400 imag diff=0.000011921500
Output varied for sample 2043: real diff=0.000014121700 imag diff=0.000008035500
Output varied for sample 2044: real diff=0.000014166000 imag diff=0.000017200000
Output varied for sample 2045: real diff=0.000031228399 imag diff=0.000029560500
Output varied for sample 2046: real diff=0.000055711000 imag diff=0.000056529901
Output varied for sample 2047: real diff=2047.999877929688 imag diff=2047.999755859375
2048 out of 2048 didn't match.

**Comment by ghostop14** [comment]
Probably also important to see this definition from higher up....
struct DComplexStruct {
	double real;
	double imag;
};

typedef struct DComplexStruct DComplex;

**Comment by AlexHild** [comment]
If I got your code correctly your test signal contains only one frequency corresponding to the last sample of the FFT result. Can you please post the last value for both implementations? Perhaps it's just both implementations having different scale factors?

**Comment by ghostop14** [comment]
Thanks Alex, yes it's just for testing.  I started hunting down the code because when plotted the output of the native block and my block they weren't overlaying like all of the OpenCL/native implementations were so I started hunting for the source of the discrepency.

Here's the last sample outputs running double precision on an NVIDIA GTX 1070.  I had other issues with single precision sin/cos functions so everything else got switched to double and the discrepancies went away.

GNURadio: real = 0.000180715608 imag: 2047.999755859375
OpenCL: real = 0.000175664667 imag: 2048.000000000000

**Comment by ghostop14** [comment]
Just to double-check the scaling factor theory (I didn't think there would be one unless it was explicitly set in the signal processing blocks and I didn't see one), I checked a quick ratio on the output values and they're inconsistent which leads me to believe there isn't a scaling factor in play.  And I know the gnuradio output is accurate on trig functions to at least 12 digits.

**Comment by tingxingdong** [comment]
Output varied for sample 2046: real diff=0.000055711000 imag diff=0.000056529901. This is single or double?

**Comment by bragadeesh** [comment]
there is no way for 2 independent fft implementations to produce bit exact answers with floating point. Are you saying that the numerical difference with single precision (CLFFT_SINGLE) is bigger than what's allowable in your app? And you do not see the problem with CLFFT_DOUBLE?

Or are you saying library is producing totally wrong results with CLFFT_SINGLE?

**Comment by ghostop14** [comment]
I know the single/double thing gets intermingled in here.  My first real question is "am I doing anything obviously wrong in setting up the fft plan or does it look like it should produce correct results"?  Take into account that the first part I posted that had the CLFFT_SINGLE was just asking if the flow was right.  I'm actually using CLFFT_DOUBLE in the running code (it first detects if the hardware supports it and sets up accordingly).  When in doubt I always assume I coded something wrong and work from there, so I wanted to make sure I hadn't made any obvious flow mistakes in the plan setup.

The second issue is on the comparison of the output.  I am using double precision (CLFFT_DOUBLE) in the test code that generated those numbers.  I agree bitwise exact matches are unlikely, but thought going in was that I would expect the output to match out to 10-12 decimal places.  What I see is that the differences start to come in around the 4th or 5th decimal place and I can't explain why, which experience says I'm probably doing something not quite right.  And when I look at the two FFT's from real signals overlaid on top of each other the peaks don't quite line up (which is what sent me hunting for the issue).  I'm really hoping I just missed something simple.

**Comment by bragadeesh** [comment]
from the first post, I do not see anything wrong in plan setup. you are doing single precision 1D complex fft of size 2048 with default batch size of 1. seems ok.

the expectations that results will differ only 10th digit or some nth digit is wrong. results could differ in variety of ways depending on input signal and corresponding output. for example, the reference output value at index 0 could be very big, lets say 10e7. the next index 1 could have extremely small value like 0.2. Now the library might produce results where the first index is very close to 10e7 but the index 1 could be 0.3. the difference in this case starts at the first digit (0.2 vs 0.3), but this is considered ok, because there is a high value in the output spectrum and compared to that 0.2 is insignificant; what I am saying is numerical comparison is not just a simple thing as point wise comparison or nth digit comparison etc; you need to figure out what is an acceptable comparison depending on your app. you could do for example normalized root-mean square error or you could do a round-trip forward & inverse fft and compare your original signal etc etc .. there is no 1 answer for this.

when you say results are not lining up, do you mean they are close enough? your definition of 'not quite lining up' is vague, what I am asking is are the results reasonably correct (shape of the spectrum same etc but numerically differing slightly) or are they totally wrong?

**Comment by ghostop14** [comment]
They're close but in every other block I've worked up it's an exact trace CPU over OpenCL.  For FFT it isn't and it led me to think I was doing something wrong.  Thanks for the explanation.  Sounds like it may actually have been okay?

Would you know behind the scenes in the clFFT library, if it's CLFFT_SINGLE is set, does it use the float data types for any trig functions and 'double' for CLFF_DOUBLE?  I have seen that make a difference when running OpenCL on a CPU with the intel drivers which is why I'm asking just to cover my bases.

Thanks!

**Comment by bragadeesh** [comment]
FFT is complex arithmetic, so numerical difference is expected. I am assuming what you are seeing is just that, something that is expected.

No trig function are used for both CLFFT_SINGLE and CLFF_DOUBLE. The twiddles are pre-computed on host with double precision. When transform runs, it uses single precision data type for all internal arithmetic when CLFFT_SINGLE plan is used and similarly double types for CLFF_DOUBLE

**Comment by ghostop14** [comment]
Thanks for all the insight!  I'll just take it as normal.

**Comment by AlexHild** [comment]
Looking at the result from both implementations you posted it seems that the OpenCL values are the more exact ones. For your single frequency signal with amplitude one I expect the imaginary part to be exactly 2048 while the real part should be exactly zero. For the imaginary part clFFT is completely right. The real part is closer to 0 than gnuradio.
