### ISSUE TITLE
Supress "warnings generated" message at runtime

### ISSUE THREAD

**Issue by ghostop14** [clMathLibraries/clFFT#192]
Hi, when I run an app with clFFT, I get a "warnings generated" message output but everything runs fine.  Is there a way to supress the message so the end-user doesn't see it?

**Comment by bragadeesh** [comment]
Can you post the warnings message here? It is coming from the OpenCL runtime compiler. 
Please provide additional details on problem parameters, OS, driver etc.

**Comment by bragadeesh** [comment]
Closing this for now; please reopen if needed
