### ISSUE TITLE
CLFFT_INPLACE not working

### ISSUE THREAD

**Issue by skn123** [clMathLibraries/clFFT#193]
Or am I missing out something? This is the code that I am using. It is a "hacked" version of the fft1d.c example. I have indicated what works and what does not work in the code:
a.) UBuntu 16.04.2LTS
b.) AMDGPUPRO 17.10 driver
c.) [R9 270X graphics card ](https://community.amd.com/message/2800587)(hacked and made it working! - Supposedly unsupported by AMD)
d.) AMD 7850 Kaveri CPU
e.) Works perfectly fine when context is CPU

```
  #define __CL_ENABLE_EXCEPTIONS
  #include <CL/cl.hpp>
  #include <utility>
  #include <cstdio>
  #include <cstdlib>
  #include <iostream>
  /* No need to explicitely include the OpenCL headers */
  #include <clFFT.h>
  int main(void)
  {
    size_t N = 16;
    cl_int err;
    
    // Allocate memory
    float* X = new float[2*N];
    
    float* Y = new float[2*N];
    
    int print_iter = 0;
    std::cout << "Input: " << std::endl;
    while(print_iter<N) 
    {
      float x = (float)print_iter;
      float y = (float)print_iter*3;
      X[2*print_iter  ] = x;
      X[2*print_iter+1] = y;
      std::cout << "(" << x << ", " << y << "), ";
      ++print_iter;
    }
    std::cout << std::endl;  
    
    try 
    {
    std::vector<cl::Platform> platformList;

    // Pick platform
    cl::Platform::get(&platformList);

    // Pick first platform
    cl_context_properties cprops[] = {CL_CONTEXT_PLATFORM, (cl_context_properties)(platformList[0])(), 0};

    cl::Context context(CL_DEVICE_TYPE_GPU, cprops);

    // Query the set of devices attched to the context
    std::vector<cl::Device> devices = context.getInfo<CL_CONTEXT_DEVICES>();
    
    //  Copy data to the buffer
    cl::Buffer bufX = cl::Buffer(context, CL_MEM_READ_ONLY, 2*N * sizeof(float));
    cl::Buffer bufY = cl::Buffer(context, CL_MEM_READ_ONLY, 2*N * sizeof(float));
    cl::CommandQueue queue(context, devices[0], 0);
    
    //  Copy the data to the device
    queue.enqueueWriteBuffer(bufX, CL_TRUE, 0, 2*N * sizeof(float), X);    

    // FFT library realted declarations
    clfftSetupData fftSetup;
    clfftPlanHandle planHandle;
    clfftDim dim = CLFFT_1D;
    size_t clLengths[1] = {N};
    
    //  Setup clFFT
    err = clfftInitSetupData(&fftSetup);
    std::cout << err << std::endl;
    err = clfftSetup(&fftSetup);
    std::cout << err << std::endl;

    // Create a default plan for a complex FFT.
    err = clfftCreateDefaultPlan(&planHandle, context(), dim, clLengths);

    // Set plan parameters
    err = clfftSetPlanPrecision(planHandle, CLFFT_SINGLE);
    err = clfftSetLayout(planHandle, CLFFT_COMPLEX_INTERLEAVED, CLFFT_COMPLEX_INTERLEAVED);
    err = clfftSetResultLocation(planHandle, CLFFT_OUTOFPLACE);

    // Bake the plan
    err = clfftBakePlan(planHandle, 1, &( queue() ), NULL, NULL);
    
    //  Execute the plan
    err = clfftEnqueueTransform(planHandle, CLFFT_FORWARD, 1, &queue(), 0, NULL, NULL, &(bufX()), &(bufY()), NULL);
    
    //  Copy the result back to the host
    //queue.enqueueReadBuffer(bufX, CL_TRUE, 0, 2 * N * sizeof(float), Y);
    queue.enqueueReadBuffer(bufY, CL_TRUE, 0, 2 * N * sizeof(float), Y); 
    //  print the output array
    print_iter = 0;
    std::cout << "Result: " << err<< std::endl;
    while(print_iter<N) 
    {
      std::cout << "(" << Y[2*print_iter] << ", " << Y[2*print_iter+1] << "), ";
      ++print_iter;
    }
    std::cout << std::endl;   
    
    // Release the plan.
    clfftDestroyPlan( &planHandle );

    //Release clFFT library.
    clfftTeardown( );    
  }
  catch (cl::Error err1) 
  {
    return EXIT_FAILURE;
  }
  delete []X;
  delete []Y;
  return 1;
}//end of function
```
Result of using CL_FFTINPLACE
Input: 
(0, 0), (1, 3), (2, 6), (3, 9), (4, 12), (5, 15), (6, 18), (7, 21), (8, 24), (9, 27), (10, 30), (11, 33), (12, 36), (13, 39), (14, 42), (15, 45), 
0
0
Result: 0
(0, 0), (1, 3), (2, 6), (3, 9), (4, 12), (5, 15), (6, 18), (7, 21), (8, 24), (9, 27), (10, 30), (11, 33), (12, 36), (13, 39), (14, 42), (15, 45), 

Result of using CL_FFTOUTOFPLACE
I ran the program immediately and this is what I got:
Input: 
(0, 0), (1, 3), (2, 6), (3, 9), (4, 12), (5, 15), (6, 18), (7, 21), (8, 24), (9, 27), (10, 30), (11, 33), (12, 36), (13, 39), (14, 42), (15, 45), 
0
0
Result: 0
(-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), (-nan, -nan), 

I re-ran it again and now the answer seems correct
Input: 
(0, 0), (1, 3), (2, 6), (3, 9), (4, 12), (5, 15), (6, 18), (7, 21), (8, 24), (9, 27), (10, 30), (11, 33), (12, 36), (13, 39), (14, 42), (15, 45), 
0
0
Result: 0
(120, 360), (-128.656, 16.2187), (-65.9411, -4.68629), (-43.9185, -12.0272), (-32, -16), (-24.0363, -18.6546), (-17.9411, -20.6863), (-12.7739, -22.4087), (-8, -24), (-3.2261, -25.5913), (1.94112, -27.3137), (8.03629, -29.3454), (16, -32), (27.9185, -35.9728), (49.9411, -43.3137), (112.656, -64.2187), 

So the questions are as follows:
a.) What am I doing wrong? or is this a GPU problem?
b.) I don't think this is a GPU problem as Out of place seems to work. However, why does it not work the first time? Only when I run the code for two times does it give the correct answer. I checked it with a NVIDIA card and the results were fine the first time. Is there some additional steps that I have to do before running the kernel on the GPU?

**Comment by tingxingdong** [comment]
If R9 270x is not in the product compatibility list of AMDGPU PRO 17.10. Then it means it is not stable. So ==  not guarantee. You may need a newer card or an older driver.

**Comment by skn123** [comment]
I understand it is not stable. It can explain the appearance of nan. However what I fail to understand is why the INPLACE method fails ? Where in the code should I take a look to understand the difference between this and OUTOFPLACE ?

**Comment by tingxingdong** [comment]
driver instable meanings the kernel may or may not launch, memcpy may or may not executed.  So you see the input data is not touched

**Comment by skn123** [comment]
So where in the code is it taking place. Can you please point me to that location ?

**Comment by bragadeesh** [comment]
I have to close this as it is driver support issue and not really to do with library
