### ISSUE TITLE
clfftInitSetupData linker errors at low optimisation levels

### ISSUE THREAD

**Issue by ajtribick** [clMathLibraries/clFFT#194]
I tried to get started with clFFT and ran into an odd issue when trying to compile the example file fft1d.c. it appears that clfftInitSetupData doesn't work at low optimisation levels, failing in the linker with "undefined reference to 'clfftInitSetupData'" and returning with exit code 1. I'm using Ubuntu 17.04 and linking against the 2.12.2 version.

Compiling with gcc 6.3.0 fails with -O0 and links at -O1, -O2, -O3
Compiling with clang 4.0.0 fails with -O0 and -O1 and links at -O2 and -O3.

Based on [this StackOverflow question](https://stackoverflow.com/questions/16740515/simple-c-inline-linker-error) I tried editing clFFT.h so that clfftInitSetupData is declared as static __inline rather than just __inline, which seems to fix it but not sure if that's the correct way to go.

**Comment by tingxingdong** [comment]
which GPU do you use?

**Comment by bragadeesh** [comment]
That change appears to be fine, the clfftInitSetupData is fully defined function in header that deals with versioning; you can test your change works by querying for version with clfftGetVersion and make sure you get what you expect.
