### ISSUE TITLE
1D FFT on multiple lines

### ISSUE THREAD

**Issue by FabioGibiino** [clMathLibraries/clFFT#195]
Hello is there a way to get the 1D fft on multiple lines at the same time?
I have a bunch of signals, all having the same length, and I would like to have the 1D fft for each of them.
I was going to loop over all the signals and run the 1D clfft for each of them. Do you think that running them all together would gain better performance? Is there a way to do that with clfft?
In other words I would like to have an intermediate result of a 2D fft, before transposing and transforming in the other direction.
Thanks a lot!
Fabio

**Comment by kknox** [comment]
Yes, when you create an FFT plan, it has a default batch value of 1, but you can [increase the batch value](http://clmathlibraries.github.io/clFFT/index.html#clFFTEff) with [clfftSetPlanBatchSize()](http://clmathlibraries.github.io/clFFT/clFFT_8h.html#a745f5b98386b73f9fc04395d30140d71).

**Comment by FabioGibiino** [comment]
Thanks a lot for your answer!

Is there any example that you could point me to please? 
Or could you tell me which are the parameters to change besides batchsize? 

If concatenate 2 complex signals (each with real/imaginary interleaved) and I set the batchsize to 2, the 1D fft looks right for the first signal, but wrong for the second.
How do I use clfftSetPlanDistance? in the documentation it refers to clfftSetPlanDimension() but I can't find this method.

Thank you so much!

**Comment by FabioGibiino** [comment]
I figured it out myself: I was setting the wrong sizes! 
The size of the fft should be set to the size of each single fft line; whereas I was setting it to the size of the whole buffer.

**Comment by kknox** [comment]
Correct, our kernels need the stride to jump between each individual FFT.  Glad you figured it out.

**Comment by FabioGibiino** [comment]
Hello again 

I have a row-major array and I would like to run the 1D fft for each Column.
I just set the strideX equal to the batch size (i.e. the number of columns) using clfftSetPlanInStride. Is there anything else I have to set? The plane dimension is the number of rows right? 
It looks like the first signal is correctly transformed, but the following ones seem truncated, like shifted... do I need to set some padding anywhere?

Thank you so much for the help!

**Comment by FabioGibiino** [comment]
This is my test code for 3 arrays columns of 64 samples each

       int NumSamples = 64;
       int NumBatches = 3;        
       clfftPlanHandle m_planHandle;
	size_t sizes[1] = { NumSamples };
	size_t strides[1] = { NumBatches };

	clfftCreateDefaultPlan(&m_planHandle, m_context, CLFFT_1D, sizes);
	clfftSetResultLocation(m_planHandle, CLFFT_OUTOFPLACE);
	clfftSetPlanBatchSize(m_planHandle, NumBatches);
	clfftSetPlanInStride(m_planHandle, CLFFT_1D, strides);
	clfftBakePlan(m_planHandle, 1, &m_queue, NULL, NULL);   

	clfftEnqueueTransform(m_planHandle, CLFFT_FORWARD, 1, &m_queue, 0, NULL, NULL, &clBufIN, &clBufOUT, NULL);

The first signal spectrum is fine, but the other two look like the input signal was cropped. 
Do you have any suggestion?

**Comment by bragadeesh** [comment]
To go from the first column to second, how much is the offset? I am assuming it is 1 from what you are saying. So you to need set the distances to 1. Look into clfftSetPlanDistance.

**Comment by FabioGibiino** [comment]
Yes that was it! :)
 Thank you so much!
