### ISSUE TITLE
Find best approximated size supported by clfft

### ISSUE THREAD

**Issue by FabioGibiino** [clMathLibraries/clFFT#196]
Hello 
Given a certain size, I would like to find the best approximation of it that is supported by clfft.
Do you have any suggestion for that?
Thanks a lot!
Fabio Gibiino

**Comment by bragadeesh** [comment]
Though clFFT supports any size that is any combination of power of 2,3,5,7,11,13, it is best to choose sizes that is power of 2 for perf reasons.
