### ISSUE TITLE
Ambiguous call of sqrt on size_t

### ISSUE THREAD

**Issue by jakirkham** [clMathLibraries/clFFT#198]
This [line]( https://github.com/clMathLibraries/clFFT/blob/v2.12.2/src/library/plan.cpp#L168 ) seems to be causing me some issues with compilation. It seems that `sqrt` is being called with `size_t` and expected to provide `size_t`. Should some casting and some round/ceil/trunc be applied?

**Comment by tingxingdong** [comment]
this may be casted to double

**Comment by jakirkham** [comment]
Yep, I agree. Did that in PR ( https://github.com/clMathLibraries/clFFT/pull/199 ). Seems to resolve the issue.
