### ISSUE TITLE
Non-square 2D FFT (errors) - Valid supported lengths

### ISSUE THREAD

**Issue by skn123** [clMathLibraries/clFFT#228]
I am finding a major issue with clFFT. I have the following configuration w.r.t the code:
a.) Latest checkout from repo.
b.) Having the following H/W configuration:
Number of platforms:				 2
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
  Platform Name:				 Portable Computing Language
  Platform Vendor:				 The pocl project
  Platform Extensions:				 cl_khr_icd
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.1 AMD-APP (2814.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 

  Platform Name:				 Portable Computing Language
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1022h
  Max compute units:				 16
  Max work items dimensions:			 3
    Max work items[0]:				 4096
    Max work items[1]:				 4096
    Max work items[2]:				 4096
  Max work group size:				 4096
  Preferred vector width char:			 16
  Preferred vector width short:			 16
  Preferred vector width int:			 8
  Preferred vector width long:			 4
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 16
  Native vector width int:			 8
  Native vector width long:			 4
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 3000Mhz
  Address bits:					 64
  Max memory allocation:			 4294967296
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 128
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 8388608
  Global memory size:				 14663213056
  Constant buffer size:				 4194304
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 4194304
  Kernel Preferred work group size multiple:	 8
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Platform ID:					 0x7fe5a9935020
  Name:						 pthread-AMD Ryzen 7 1700 Eight-Core Processor
  Vendor:					 AuthenticAMD
  Device OpenCL C version:			 OpenCL C 1.2 pocl
  Driver version:				 1.1
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-znver1
  Extensions:					 cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_spir cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64

  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560]
  Device Topology:				 PCI[ B#34, D#0, F#0 ]
  Max compute units:				 14
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1250Mhz
  Address bits:					 64
  Max memory allocation:			 3650722201
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 26607
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 4294967296
  Constant buffer size:				 3650722201
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 3650722201
  Max global variable size:			 3650722201
  Max global variable preferred total size:	 4294967296
  Max read/write image args:			 64
  Max on device events:				 1024
  Queue on device max size:			 8388608
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7fe5a33e6a30
  Name:						 gfx803
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 2814.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

c.) I tried playing around with the example code in 2D. I wanted to check for a supported dimension. I selected a dimension of 5 (i.e., N0, N1 = 5). the result is shown:
Platform found: Portable Computing Language
Device found on the above platform: pthread-AMD Ryzen 7 1700 Eight-Core Processor

Performing fft on an two dimensional array of size N0 x N1 : 5 x 5
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 

fft result: 
(12.500000, 12.500000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
(0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
(0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
(0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
(0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) (0.000000, 0.000000) 
And it confirms with what fftw reports (checked it in Octave).

Now,  I changed the dimensions to N0=4 and N1=5 (4 rows and 5 columns). Note that the matrix is not a square matrix but the dimensions are supported by clFFT. This is what I get:
Platform found: Portable Computing Language
Device found on the above platform: pthread-AMD Ryzen 7 1700 Eight-Core Processor

Performing fft on an two dimensional array of size N0 x N1 : 4 x 5
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 
(0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) (0.500000, 0.500000) 

fft result: 
(8.495893, 8.500000) (0.503536, 0.500000) (0.497035, 0.500000) (0.503536, 0.500000) (0.961790, -1.894016) 
(0.961790, -1.894016) (-0.319927, 0.633399) (-0.321936, 0.627217) (-0.319927, 0.633399) (2.098526, 0.329434) 
(2.098526, 0.329434) (-0.701261, -0.108538) (-0.696003, -0.112359) (-0.701261, -0.108538) (0.335170, 2.097617) 
(0.335170, 2.097617) (-0.113476, -0.700479) (-0.108217, -0.696658) (-0.113476, -0.700479) (-1.891379, 0.966965) 

Obviously the result is incorrect; Comparison result using fftw in Octave:
>> a=[0.5 0.5 0.5 0.5]+i*[0.5 0.5 0.5 0.5]
a =

   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i

>> b=conj(a')*ones(1,5)
b =

   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i
   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i
   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i
   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i   0.50000 + 0.50000i

>> fft2(b)
ans =

   10 + 10i    0 +  0i    0 +  0i    0 +  0i    0 +  0i
    0 +  0i    0 +  0i    0 +  0i    0 +  0i    0 +  0i
    0 +  0i    0 +  0i    0 +  0i    0 +  0i    0 +  0i
    0 +  0i    0 +  0i    0 +  0i    0 +  0i    0 +  0i

I think the problem is related to plan baking; and that too when we are building a column plan. 
Can someone please explain why this may be happening? @bragadeesh @kknox

**Comment by bragadeesh** [comment]
@skn123 
clFFT has not seen active maintenance/testing in a while; but functionality you are describing was tested and is expected to work in the supported platforms; It could be the environment, problem with unsupported gpu or ocl platform

**Comment by skn123** [comment]
@bragadeesh I understand that. I am getting the same results when I use any AMD or NVIDIA or Intel GPU/CPU. That is why I have reported this bug. I am also aware that this library has not seen any update. I am unable to fathom why it should *only* behave badly for non-square matrices. Can you also confirm from your end that this bug is repeatable on any supported platforms? If so, maybe you can keep this open and someone else can figure out a way to fix this. I am suspecting this has something to do with the logic in the clfftBakePlan function.

**Comment by clSharp** [comment]
Just had my unit tests running on version 2.12.2 of clFFT and I can not reproduce your problems. Testet all combinations of 2D FFT with lengths 4 and 5, inplace and out-of-place, forward and backward with platforms Intel (GPU+CPU), NVidia(GPU) and AMD(CPU). All results were correct.

Are you sure you are calling clFFT correctly? Perhaps there is a problem with your strides or other parameters? Can you test if 2.12.2 is working correctly for you? If yes we know that the problem is not on your side.

**Comment by skn123** [comment]
@clSharp indeed that specific tag works! I think I will use that tag instead.

**Comment by clSharp** [comment]
I think that's a reason not to close this issue. It seems that there is a regression in one of the commits after 2.12.2.

**Comment by clSharp** [comment]
@skn123: As you have a running test environment: Would you mind to bisect the commits to find the one introducing the regression?
