### ISSUE TITLE
clFFT vs CUFFT

### ISSUE THREAD

**Issue by sschaetz** [clMathLibraries/clFFT#26]
I'm comparing CUFFT on GeForce Titan and clFFT on W9000 (and GeForce Titan). The tests run 500ms each. I'm not benchmarking the first run of each FFT call.

512x512 complex to complex in place 1 batch

Titan + clFFT min 246.000000 max 3132.000000 mean 284.540125 stdev 90.330571 runs 1757
Titan + CUFFT min 75.000000 max 447.000000 mean 84.112308 stdev 13.193472 runs 5939

W9000 + clFFT min 263.000000 max 609.000000 mean 281.706479 stdev 21.922476 runs 1775

Is this performance of clFFT expected/known or am I doing something wrong?

**Comment by tompano33** [comment]
Guys,

I just found this thread while benchmarking 1D FFTs. For 4096 points I found that the clFFT is nearly 5-10 times slower than cuFFT on a GTX 770. Anyone here who can confirm this or better give a hint how to improve that number for clFFT?

Thomas

System: Intel i7 4xxx, Windows 7 64-bit, CUDA 6.5, GTX 770

client -p 100 -x 4096 -b 1024

========================StdDev ( 2 )========================
clFFT[ 0 ]: Pruning 1 samples out of 100

===========================clFFT============================
        Handle:                   1
        Kernel:            043634E8
     OutEvents:            044D5550
        Length:              (4096)
         Batch:                1024
  Input Stride:                 (1)
 Output Stride:                 (1)
   Global Work:            (262144)
        Gflops:                       53.7292
     Time (ns):                                    4,683,824

**Comment by bragadeesh** [comment]
clFFT was originally and continues to be designed and optimized for AMD GPUs. Hence performance is best on AMD GPUs with AMD OpenCL runtime. Since the library is on the OpenCL platform, nothing prevents it from being run on other OpenCL runtimes. But functional and performance quality on other platforms depend on a variety of things including architectural differences and runtime performance etc.

**Comment by tompano33** [comment]
Thanks a lot for this clarification. Actually we were testing clFFT on an ARM Mali GPU and did wonder to which degree clFFT is an optimal implementation. I realize now, that hardware specific code is more significant, than we anticipated. On an ARM Mali-T628 MP6 GPU we achieve around 1 GFLOPS for an 4096 point FFT if at least executed 16-32 times in parallel. Still extremely useful, but could be more ;)
