### ISSUE TITLE
Enhance transpose kernel generator to support additional sizes

### ISSUE THREAD

**Issue by kknox** [clMathLibraries/clFFT#3]
The kernel transpose generator can only generate kernels whose sizes in the X and the Y dimensions that are mod-32. Given the fact that our FFT kernel generators support prime factors of 3 and 5, we have weak coverage of the vector sizes we support. The transpose kernel generator should be extended to handle all sizes that the FFT kernel generator supports, if not arbitrary dimension lengths.

**Comment by bragadeesh** [comment]
This feature is supported now ..
