### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by proteneer** [clMathLibraries/clFFT#39]
Has anyone had much luck getting this to work on OS X and the intel CPUs/integrated GPUs (or in general on CPUs/integrated GPUs on Linux)?

I kept getting this:

OPENCL_V< CLFFT_INVALID_WORK_GROUP_SIZE > (1223): clEnqueueNDRangeKernel failed

**Comment by pavanky** [comment]
This is a problem with Intel Runtime that can not be fixed easily in the library. The runtime is forcing you to serialize the code which in effect forces you to write essentially what are two different code bases.
