### ISSUE TITLE
Latex formulae in documentation not rendering correctly

### ISSUE THREAD

**Issue by tbs1980** [clMathLibraries/clFFT#46]
I see that the documentation generated by doxygen (version 1.8.6 in ubuntu 14.04) using /doc/clFFT.doxy does not render the maths formula correctly. I managed to get this right by changing 

    USE_MATHJAX            = NO 

in line 1412 of clFFT.doxy. 
It will be great if you guys can update http://clmathlibraries.github.io/clFFT/ pages so that the formulae are displayed properly. Many thanks in advance.

**Comment by bragadeesh** [comment]
fixed with commit 125c47ac05c382b3fc879edc0227e86f980ddcd1
