### ISSUE TITLE
clFFT displays (possibly) unnecessary log messages even in release mode

### ISSUE THREAD

**Issue by pavanky** [clMathLibraries/clFFT#47]
This is in relation to https://github.com/arrayfire/arrayfire/issues/171

The output of the fft seems to be correct. However the following message is displayed only on AMD hardware.

```
OPENCL_V< CLFFT_INVALID_PLAN > (3083): fftRepo.getPlan failed
```

This is for a real to complex transform. Input of size 8 elements.

**Comment by kknox** [comment]
Our library should not be printing anything to `stdout`.  We should be able to have an answer to you on monday, when we're all back in office.

**Comment by pavanky** [comment]
@kknox Again, my bad. It is `stderr` **not** `stdout`.  This issue can be closed if that is expected behavior.

**Comment by kknox** [comment]
In private.h:273, looks like we unconditionally print an error string to stderr.  We could guard the `terr` print statements with something that enables it only with debug builds.  Are you OK with printing to stderr for release builds?

**Comment by pavanky** [comment]
@kknox I think that behavior is OK in debug mode but not in release mode.
