### ISSUE TITLE
Examples for 2D and 3D FFT

### ISSUE THREAD

**Issue by skn123** [clMathLibraries/clFFT#51]
Is there any example / can some examples be provided for computing 2D and 3D FFT?

**Comment by bragadeesh** [comment]
It should be fairly straightforward. The API documentation should answer your questions and you would follow the 1D example shown on the main page. If you are computing real transforms, then you have to read the documentation ( http://clmathlibraries.github.io/clFFT/ ) closely and see the section: 'FFTs of Real Data'. Let us know if anything is unclear.

**Comment by pavanky** [comment]
@bragadeesh Pradeep's id is @9prady9. Can you make him the assignee ?

**Comment by bragadeesh** [comment]
I could not assign to Pradeep. It will only let me assign to someone in the members list and Pradeep is not on the list.

**Comment by bragadeesh** [comment]
Thanks to @9prady9 ; we now have examples for 1D, 2D, 3D in the code; look in examples directory

**Comment by skn123** [comment]
Indeed, I will look into it. However, a question that I have is as follows:
Is it necessary that the images should be dyadic in size (or will they be made dyadic by zero padding?)

**Comment by 9prady9** [comment]
@skn123 I think the user has to take care of padding the data to optimal sizes.
