### ISSUE TITLE
Kernel code compilation error

### ISSUE THREAD

**Issue by machta** [clMathLibraries/clFFT#66]
clfftBakePlan() gives me this strange error: http://pastebin.com/TLYcDm6e.

It happens on Ubuntu (not on Windows) with releases 2.2 and 2.4.

I was able to fix this problem by exporting a new value for the environment variable LC_NUMERIC ("en_US.UTF-8" instead of the previous "cs_CZ.UTF-8").

My guess is that while the implementation internally generates some code it uses formatting of decimal numbers according to the localization set for the environment, hence the Czech comma instead of the English period.

**Comment by bragadeesh** [comment]
Hi, That URL that shows the error is not working. Can you update?
Are you saying that your default was your Czech locale and you fixed this by changing to English? Hopefully, this tip should help anyone running into this issue.

**Comment by machta** [comment]
The link is OK for me but here it is anyway:

			BUILD LOG
************************************************
"/tmp/OCL12787T7.cl", line 19: warning: OpenCL extension is now part of core
  #pragma OPENCL EXTENSION cl_khr_fp64 : enable
                           ^

"/tmp/OCL12787T7.cl", line 26: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 27: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 28: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 29: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 30: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 31: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 32: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 33: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 34: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 35: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 36: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 37: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 38: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 39: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 40: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 41: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 42: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 43: error: too many initializer values
  (double2)(1,0000000000000000000000000000000000, -0,0000000000000000000000000000000000),
                                                  ^

"/tmp/OCL12787T7.cl", line 44: error: integer constant is too large
  (double2)(0,9980267284282715589682766221812926, -0,0627905195293133738809743249476014),
              ^

"/tmp/OCL12787T7.cl", line 44: error: invalid octal digit
  (double2)(0,9980267284282715589682766221812926, -0,0627905195293133738809743249476014),
                                                         ^

"/tmp/OCL12787T7.cl", line 44: error: too many initializer values
  (double2)(0,9980267284282715589682766221812926, -0,0627905195293133738809743249476014),
                                                     ^

"/tmp/OCL12787T7.cl", line 45: error: integer constant is too large
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
              ^

"/tmp/OCL12787T7.cl", line 45: error: integer constant is too large
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
                                                     ^

"/tmp/OCL12787T7.cl", line 45: error: too many initializer values
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
                                                     ^

"/tmp/OCL12787T7.cl", line 46: error: integer constant is too large
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246287295794218152878),
              ^

"/tmp/OCL12787T7.cl", line 46: error: integer constant is too large
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246287295794218152878),
                                                     ^

"/tmp/OCL12787T7.cl", line 46: error: too many initializer values
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246287295794218152878),
                                                     ^

"/tmp/OCL12787T7.cl", line 47: error: integer constant is too large
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
              ^

"/tmp/OCL12787T7.cl", line 47: error: integer constant is too large
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
                                                     ^

"/tmp/OCL12787T7.cl", line 47: error: too many initializer values
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
                                                     ^

"/tmp/OCL12787T7.cl", line 48: error: integer constant is too large
  (double2)(0,9510565162951535311819384332920890, -0,3090169943749473957517182043375215),
              ^

"/tmp/OCL12787T7.cl", line 48: error: integer constant is too large
  (double2)(0,9510565162951535311819384332920890, -0,3090169943749473957517182043375215),
                                                     ^

"/tmp/OCL12787T7.cl", line 48: error: too many initializer values
  (double2)(0,9510565162951535311819384332920890, -0,3090169943749473957517182043375215),
                                                     ^

"/tmp/OCL12787T7.cl", line 49: error: integer constant is too large
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
              ^

"/tmp/OCL12787T7.cl", line 49: error: integer constant is too large
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
                                                     ^

"/tmp/OCL12787T7.cl", line 49: error: too many initializer values
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
                                                     ^

"/tmp/OCL12787T7.cl", line 50: error: integer constant is too large
  (double2)(0,9048270524660194658039813475625124, -0,4257792915650727150200793857948156),
              ^

"/tmp/OCL12787T7.cl", line 50: error: integer constant is too large
  (double2)(0,9048270524660194658039813475625124, -0,4257792915650727150200793857948156),
                                                     ^

"/tmp/OCL12787T7.cl", line 50: error: too many initializer values
  (double2)(0,9048270524660194658039813475625124, -0,4257792915650727150200793857948156),
                                                     ^

"/tmp/OCL12787T7.cl", line 51: error: integer constant is too large
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
              ^

"/tmp/OCL12787T7.cl", line 51: error: integer constant is too large
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
                                                     ^

"/tmp/OCL12787T7.cl", line 51: error: too many initializer values
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
                                                     ^

"/tmp/OCL12787T7.cl", line 52: error: integer constant is too large
  (double2)(0,8443279255020150753097141205216758, -0,5358267949789966566598309327673633),
              ^

"/tmp/OCL12787T7.cl", line 52: error: integer constant is too large
  (double2)(0,8443279255020150753097141205216758, -0,5358267949789966566598309327673633),
                                                     ^

"/tmp/OCL12787T7.cl", line 52: error: too many initializer values
  (double2)(0,8443279255020150753097141205216758, -0,5358267949789966566598309327673633),
                                                     ^

"/tmp/OCL12787T7.cl", line 53: error: integer constant is too large
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
              ^

"/tmp/OCL12787T7.cl", line 53: error: integer constant is too large
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
                                                     ^

"/tmp/OCL12787T7.cl", line 53: error: too many initializer values
  (double2)(0,9921147013144778759041741977853235, -0,1253332335643042583228634612169117),
                                                     ^

"/tmp/OCL12787T7.cl", line 54: error: integer constant is too large
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
              ^

"/tmp/OCL12787T7.cl", line 54: error: integer constant is too large
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
                                                     ^

"/tmp/OCL12787T7.cl", line 54: error: too many initializer values
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
                                                     ^

"/tmp/OCL12787T7.cl", line 55: error: integer constant is too large
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
              ^

"/tmp/OCL12787T7.cl", line 55: error: integer constant is too large
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
                                                     ^

"/tmp/OCL12787T7.cl", line 55: error: too many initializer values
  (double2)(0,9297764858882513472337905113818124, -0,3681245526846779747565108209528262),
                                                     ^

"/tmp/OCL12787T7.cl", line 56: error: integer constant is too large
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
              ^

"/tmp/OCL12787T7.cl", line 56: error: integer constant is too large
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
                                                     ^

"/tmp/OCL12787T7.cl", line 56: error: too many initializer values
  (double2)(0,8763066800438635839398671123490203, -0,4817536741017153234523107130371500),
                                                     ^

"/tmp/OCL12787T7.cl", line 57: error: integer constant is too large
  (double2)(0,8090169943749474512628694355953485, -0,5877852522924731371034567928290926),
              ^

"/tmp/OCL12787T7.cl", line 57: error: integer constant is too large
  (double2)(0,8090169943749474512628694355953485, -0,5877852522924731371034567928290926),
                                                     ^

"/tmp/OCL12787T7.cl", line 57: error: too many initializer values
  (double2)(0,8090169943749474512628694355953485, -0,5877852522924731371034567928290926),
                                                     ^

"/tmp/OCL12787T7.cl", line 58: error: integer constant is too large
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286887260952880751574412),
              ^

"/tmp/OCL12787T7.cl", line 58: error: integer constant is too large
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286887260952880751574412),
                                                     ^

"/tmp/OCL12787T7.cl", line 58: error: too many initializer values
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286887260952880751574412),
                                                     ^

"/tmp/OCL12787T7.cl", line 59: error: integer constant is too large
  (double2)(0,6374239897486896344602769204357173, -0,7705132427757892532582673084107228),
              ^

"/tmp/OCL12787T7.cl", line 59: error: integer constant is too large
  (double2)(0,6374239897486896344602769204357173, -0,7705132427757892532582673084107228),
                                                     ^

"/tmp/OCL12787T7.cl", line 59: error: too many initializer values
  (double2)(0,6374239897486896344602769204357173, -0,7705132427757892532582673084107228),
                                                     ^

"/tmp/OCL12787T7.cl", line 60: error: integer constant is too large
  (double2)(0,5358267949789965456375284702517092, -0,8443279255020150753097141205216758),
              ^

"/tmp/OCL12787T7.cl", line 60: error: integer constant is too large
  (double2)(0,5358267949789965456375284702517092, -0,8443279255020150753097141205216758),
                                                     ^

"/tmp/OCL12787T7.cl", line 60: error: too many initializer values
  (double2)(0,5358267949789965456375284702517092, -0,8443279255020150753097141205216758),
                                                     ^

"/tmp/OCL12787T7.cl", line 61: error: integer constant is too large
  (double2)(0,4257792915650726595089281545369886, -0,9048270524660195768262838100781664),
              ^

"/tmp/OCL12787T7.cl", line 61: error: integer constant is too large
  (double2)(0,4257792915650726595089281545369886, -0,9048270524660195768262838100781664),
                                                     ^

"/tmp/OCL12787T7.cl", line 61: error: too many initializer values
  (double2)(0,4257792915650726595089281545369886, -0,9048270524660195768262838100781664),
                                                     ^

"/tmp/OCL12787T7.cl", line 62: error: integer constant is too large
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246009740038061863743),
              ^

"/tmp/OCL12787T7.cl", line 62: error: integer constant is too large
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246009740038061863743),
                                                     ^

"/tmp/OCL12787T7.cl", line 62: error: too many initializer values
  (double2)(0,9822872507286887211463977109815460, -0,1873813145857246009740038061863743),
                                                     ^

"/tmp/OCL12787T7.cl", line 63: error: integer constant is too large
  (double2)(0,9297764858882514582560929738974664, -0,3681245526846779192453595896949992),
              ^

"/tmp/OCL12787T7.cl", line 63: error: integer constant is too large
  (double2)(0,9297764858882514582560929738974664, -0,3681245526846779192453595896949992),
                                                     ^

"/tmp/OCL12787T7.cl", line 63: error: too many initializer values
  (double2)(0,9297764858882514582560929738974664, -0,3681245526846779192453595896949992),
                                                     ^

"/tmp/OCL12787T7.cl", line 64: error: integer constant is too large
  (double2)(0,8443279255020151863320165830373298, -0,5358267949789965456375284702517092),
              ^

"/tmp/OCL12787T7.cl", line 64: error: integer constant is too large
  (double2)(0,8443279255020151863320165830373298, -0,5358267949789965456375284702517092),
                                                     ^

"/tmp/OCL12787T7.cl", line 64: error: too many initializer values
  (double2)(0,8443279255020151863320165830373298, -0,5358267949789965456375284702517092),
                                                     ^

"/tmp/OCL12787T7.cl", line 65: error: integer constant is too large
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286886150729856126417872),
              ^

"/tmp/OCL12787T7.cl", line 65: error: integer constant is too large
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286886150729856126417872),
                                                     ^

"/tmp/OCL12787T7.cl", line 65: error: too many initializer values
  (double2)(0,7289686274214115524472390461596660, -0,6845471059286886150729856126417872),
                                                     ^

"/tmp/OCL12787T7.cl", line 66: error: integer constant is too large
  (double2)(0,5877852522924731371034567928290926, -0,8090169943749474512628694355953485),
              ^

"/tmp/OCL12787T7.cl", line 66: error: integer constant is too large
  (double2)(0,5877852522924731371034567928290926, -0,8090169943749474512628694355953485),
                                                     ^

"/tmp/OCL12787T7.cl", line 66: error: too many initializer values
  (double2)(0,5877852522924731371034567928290926, -0,8090169943749474512628694355953485),
                                                     ^

"/tmp/OCL12787T7.cl", line 67: error: integer constant is too large
  (double2)(0,4257792915650728260423818483104696, -0,9048270524660194658039813475625124),
              ^

"/tmp/OCL12787T7.cl", line 67: error: integer constant is too large
  (double2)(0,4257792915650728260423818483104696, -0,9048270524660194658039813475625124),
                                                     ^

"/tmp/OCL12787T7.cl", line 67: error: too many initializer values
  (double2)(0,4257792915650728260423818483104696, -0,9048270524660194658039813475625124),
                                                     ^

"/tmp/OCL12787T7.cl", line 68: error: integer constant is too large
  (double2)(0,2486898871648549613766476795717608, -0,9685831611286310760533524444326758),
              ^

"/tmp/OCL12787T7.cl", line 68: error: integer constant is too large
  (double2)(0,2486898871648549613766476795717608, -0,9685831611286310760533524444326758),
                                                     ^

"/tmp/OCL12787T7.cl", line 68: error: too many initializer values
  (double2)(0,2486898871648549613766476795717608, -0,9685831611286310760533524444326758),
                                                     ^

"/tmp/OCL12787T7.cl", line 69: error: invalid octal digit
  (double2)(0,0627905195293135265366402109066257, -0,9980267284282715589682766221812926),
                  ^

"/tmp/OCL12787T7.cl", line 69: error: integer constant is too large
  (double2)(0,0627905195293135265366402109066257, -0,9980267284282715589682766221812926),
                                                     ^

"/tmp/OCL12787T7.cl", line 69: error: too many initializer values
  (double2)(0,0627905195293135265366402109066257, -0,9980267284282715589682766221812926),
                                                     ^

"/tmp/OCL12787T7.cl", line 70: error: integer constant is too large
  (double2)(-0,1253332335643041473005609987012576, -0,9921147013144778759041741977853235),
               ^

"/tmp/OCL12787T7.cl", line 70: error: integer constant is too large
  (double2)(-0,1253332335643041473005609987012576, -0,9921147013144778759041741977853235),
                                                      ^

"/tmp/OCL12787T7.cl", line 70: error: too many initializer values
  (double2)(-0,1253332335643041473005609987012576, -0,9921147013144778759041741977853235),
                                                      ^

"/tmp/OCL12787T7.cl", line 71: error: integer constant is too large
  (double2)(0,9685831611286310760533524444326758, -0,2486898871648547948431939857982798),
              ^

Error limit reached.
100 errors detected in the compilation of "/tmp/OCL12787T7.cl".
Compilation terminated.
Frontend phase failed compilation.

************************************************
Exception caught in main(): Unexpected error code: -11(0xfffffff5), required 0(0x0). clfftBakePlan() ../../App/src/SignalProcessor/filter.cpp:32
Warning:  Program terminating, but clFFT resources not freed.
Please consider explicitly calling clfftTeardown( ).

**Comment by machta** [comment]
And yes, that is exactly what I am saying -- I fixed it by changing the variable from shell, then I got tired of changing it every time so I changed it in /etc/default/locale.
