### ISSUE TITLE
Error on Xeon Phi 

### ISSUE THREAD

**Issue by malcolmroberts** [clMathLibraries/clFFT#80]
I'm running clFFT on a Xeon Phi and I'm getting errors with certain problem sizes.  When I perform 1D complex-to-complex FFTs with 4, 8, 16, 32, 64, or 128 points I get the following error:

Stack dump:
0.	Running pass 'Intel OpenCL Vectorizer' on module 'Program'.
1.	Running pass 'Intel OpenCL VectorizerCore' on function '@__Vectorized_.fft_fwd'
2.	Running pass 'PacketizeFunction' on function '@__Vectorized_.fft_fwd'

Running with 2, 256, 512, or 1024 points does not produce this error.  I get similar errors for 2D transforms, but I haven't tested the problem sizes as exhaustively.

The relevant output of lspci is
Intel Corporation Xeon Phi coprocessor 5100 series

Thank you kindly,

~Malcolm

**Comment by bragadeesh** [comment]
I am closing this because it is known that OpenCL platform issues are the problem here.
