### ISSUE TITLE
Limitation about the plan size

### ISSUE THREAD

**Issue by kif** [clMathLibraries/clFFT#81]
Hi,

I am also testing clFFT as a competitor for cuFFT, mainly because most of my code-base is on OpenCL. I need to do large 3D-FFTs, typically 512^3 but more once the memory will be available.
The "hard-coded" limit of 2\*\*24 is documented for clFFT, cuFFT limits the plan to 2\*\*27. I wonder where this limit comes from and how hard it is to overcome ?

I made a debian package, would you be interested to see it integrated in the distribution ?

Cheers,

**Comment by AlexHild** [comment]
One way to overcome the limit is to subdivide your 3D FFT into three batched 1D FFTs. In this case the 2^22 limit applies per dimension.

When testing this for 2D-FFTs I found that the performance is comparable to directly using 2D-FFTs. I guess internally clFFT does the same.

**Comment by bragadeesh** [comment]
Hi, with the latest version on develop branch, the 2**24 limit has been relaxed; please try with that. Since this is work under progress, it hasn't been merged with the stable master branch. I would be interested in integrating our library with the distribution; if the licensing aspects are ok.

**Comment by kif** [comment]
On Tue, 14 Apr 2015 16:37:14 -0700
Bragadeesh Natarajan <notifications@github.com> wrote:

> Hi, with the latest version on develop branch, the 2**24 limit has been relaxed; please try with that.

I will try with the devel version soon.

> Since this is work under progress, it hasn't been merged with the stable master branch. I would be interested in integrating our library with the distribution; if the licensing aspects are ok.

If all your code is Apache, it will be straight forward (at least on the licencing point of view).

The issues I encountered until now are:
- installation into lib or lib64 depending on the architecture. Debian does that with multiarch. Fixed with debian specific patches 
- make python scripts exectuable for unix (add #!/usr/bin/env python in the header).
It is fixed via debian patches but I can submit a PR to upstream (i.e. you)
- Debian imposes strict rules on binaries: they all require a man page. this is on the todo list. I will probably split the set of python files as scripts on one side and library on the other. This is still todo
- auto-generate the doc with doxygen. I never did it but is should not be that difficult. 

All the work I did is in https://github.com/kif/clFFT/tree/debian

Cheers,
-- 
Jerome Kieffer <jerome.kieffer@terre-adelie.org>

**Comment by bragadeesh** [comment]
The debian packaging work has to be revisited later, from our side due to resource issues with no bandwidth now.

**Comment by kif** [comment]
On Thu, 21 May 2015 07:37:35 -0700
Bragadeesh Natarajan <notifications@github.com> wrote:

> The debian packaging work has to be revisited later, from our side due to resource issues with no bandwidth now.

Sorry for not communicating on that...
Actually I managed to gave debian packages, to have them building.

This is the "intent to package" of clFFT:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783084

The packaging part is done in a (couple of separated) git branches.
http://anonscm.debian.org/cgit/debian-science/packages/clfft.git/

This is still ongoing and I believe to have it available for debian in a couple of month.

Cheers,
