### ISSUE TITLE
OSX clRetainContext

### ISSUE THREAD

**Issue by Astro-Nick** [clMathLibraries/clFFT#82]
Hi,
On OSX, as part of an OpenGL view integration with a shared OpenCL context, clRetainContext() shouldn't be called - as the application does not own the context. If you create your own OpenCL context separately - this is fine.

I've removed this previously from my own build for the reason that OS X blows up if you attempt this, it may be worth adding something around this.

Nick

**Comment by bragadeesh** [comment]
Please look at: https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clRetainContext.html

It is valid and required for libraries to use this. The calling application has to make sure there is a matching destroyPlan for every createPlan call, so library can internally release the context.

**Comment by Astro-Nick** [comment]
Hi Bragadeesh,
This is a OS X special - rather than standard OpenCL. I understand what you're pointing at, however when you use OpenGL sharing with OpenCL under OS X, you are provided with a context and don't explicitly create one yourself.

"Note: Since this context is created by OpenCL, you should not retain/release it. (You should retain/release any contexts that you explicitly create.)"

https://developer.apple.com/library/mac/documentation/Performance/Conceptual/OpenCL_MacProgGuide/UsingGCDwOpenCL/UsingGCDwOpenCL.html

In the example, the context is obtained rather than clCreateContext using:
cl_context context = gcl_get_context();

It's this subtly that causes a problem when using shared contexts.

I hope that helps,
Nick

**Comment by Astro-Nick** [comment]
Hi bragadeesh - was this fixed? I just see this going from open, to clarification then closure without a comment.

Nick

**Comment by bragadeesh** [comment]
Nick,
No, nothing is done in the library for this, this sounds like an apple opencl/opengl interop issue. This has to be fixed on the stack. I understand the design restriction on apple side. But this has to be addressed by a special fork of the code, which you are already doing. We cannot change library code for this since we are in conformance with opencl.

**Comment by Astro-Nick** [comment]
Ok, understood - as long as others know that they will have the same problem on OSX.

**Comment by meshula** [comment]
It makes sense to annotate the issue in your readme. At the moment, your build instructions say only generate Linux makefiles. Your readme is therefore going to give OSX users an incorrect expectation. Minimally the readme should refer to this issue, in my opinion.

**Comment by meshula** [comment]
A note in the readme referencing this issue would be very helpful to others facing the same problem.
