### ISSUE TITLE
OSX FFTBinaryLookup::populateCache() causes crash with Intel CPU context

### ISSUE THREAD

**Issue by Astro-Nick** [clMathLibraries/clFFT#83]
Hi,
Small issue here I'm trying to trace down. Utilising a CPU context.

During the bake, the compilation of the kernel works ( build from source and build program come back with zero cl_status in FFTAction::compileKernel) however the populate cache fails here, through the stockroom generator:

cl_int FFTBinaryLookup::populateCache()
{
    // FIXME: support MSB
    this->m_header.magic_key[0] = 'C';
    this->m_header.magic_key[1] = 'L';
    this->m_header.magic_key[2] = 'B';
    this->m_header.magic_key[3] = '\0';

    std::vector<unsigned char*> data;
    cl_int err = getSingleBinaryFromProgram(this->m_program, data); <<-fails with EXC_BAD_ACCESS

It seems that commenting out the populate cache solves the problem.

**Comment by pavanky** [comment]
This seems like it is related to #84. Intel CPU on OSX is not supported.
