### ISSUE TITLE
OSX clFFT on CPU with max workgroup size of [1,1,1]

### ISSUE THREAD

**Issue by Astro-Nick** [clMathLibraries/clFFT#84]
I get this from attempting to enqueue the kernel on the CPU:
"[CL_INVALID_WORK_GROUP_SIZE] : OpenCL Error : clEnqueueNDRangeKernel failed: total work group size (243) is greater than the device can support (1)"

http://stackoverflow.com/questions/10065681/opencl-kernel-work-group-size-restriction
"Apple OpenCL doesn't support work-groups larger than [1, 1, 1] on the CPU. I have no idea why, but that's how it's been at least up to OSX 10.9.2. Larger work-groups are fine on the GPU, though."

Any way to make this work, although painfully slow, for CPU based debugging?

**Comment by pavanky** [comment]
@Astro-Nick This issue has been brought up [before](https://github.com/clMathLibraries/clFFT/issues/39). The only way to support Apple CPU is to constantly check if it is Apple CPU and change the kernels to use only one thread. This essentially means there is no easy way to fix this issue unless Apple changes their implementation.

**Comment by Astro-Nick** [comment]
Just to say I found a way around this - my pipeline is a C++ class based system in which the classes provide the calling kernel sequence for texture references, with the pipeline managing textures and kernels in memory.
I ended up refactoring so the FFT class was an interface and producing a clFFT and FFTW implementation - this allows full CPU OpenCL with FFTW, GPU/CPU hybrid OpenCL with FFTW and full GPU with clFFT. (also CPU with GPU clFFT is possible). The pipeline is working again.
So if anyone else has the same issue - I would suggest using this approach if you're on OS X only.

On the plus point - I did find an array under run/overrun running the OpenCL in GPU - but that still hasn't solved my clFFT issue of some texture sizes causing zero result to be returned.

**Comment by Astro-Nick** [comment]
Hi Folks, please note I have raised this with Apple through the developer defect tracker.
In short it makes OS X difficult to treat as a development platform without being able to support larger workgroups.

Nick

**Comment by wanderine** [comment]
Apple has known about this problem for several years. I have given up my
hopes.

- Anders
 Den 21 maj 2015 16:44 skrev "Astro-Nick" <notifications@github.com>:

**Comment by Astro-Nick** [comment]
Yup - probably makes it simple for their own development tools to support. We're probably not the only ones. I did get the triage team request further information (i.e. a system report). However I don't think design/image processing industry is really Apple's focus nowadays - hence the sad state of their graphics/compute implementations.

**Comment by pavanky** [comment]
An alternative to this would be to try and use pocl: 
https://github.com/pocl/pocl

It is an open source implementation of OpenCL. It may not have the best performance, but it might give an option for users to use the CPU.

**Comment by Astro-Nick** [comment]
Neat idea. With the FFTW rework, it means I could debug the pipeline itself on CPU but not the get down to the problem of why the OpenCL clFFT fails. I'm assuming of pocl runs slow and demonstrates that the generated code by clFFT works then it's pointing directly at the Apple/AMD runtime.

**Comment by Astro-Nick** [comment]
I just had a quick look at the pocl implementation. Currently it does not support mapping (ignoring the lack of context support or shared contexts). Mapped contexts are the preferred way of getting data in/out so it's a bit of an oversight. However once they have some of the vendor SDK self tests working then it looks like it may be worth trying but for now - it's not mature enough.
