### ISSUE TITLE
5x slowdown on AMD W8100 when using ECC

### ISSUE THREAD

**Issue by ljohnson1228** [clMathLibraries/clFFT#85]
clFFT runs 5x slower in my application when using ECC. I would normally expect 10-15% (definitely not more than 50%).

Are there any existing benchmarks in the clFFT community showing ECC performance?

**Comment by ljohnson1228** [comment]
I just discovered the Client application/benchmark provided by clFFT and indeed it shows the expected ~10% slowdown.

**Comment by ljohnson1228** [comment]
I closed this issue too quickly. The expected 10% slowdown only held true for complex to complex transforms. I ran a more through evaluation using Client.exe on AMD W8100 and got this:

(Using latest AMD drivers and clFFT pre-built binary on Windows 7)
 
![eccperformance](https://cloud.githubusercontent.com/assets/12189403/7634115/beaff0c6-fa26-11e4-9a24-1c83867f134b.png)

Here are my take aways:

1.	General FFT shows expected 10-15% slowdown in interleaved configuration
2.	With ECC disabled, Hermitian FFT exceeds general FFT performance by ~35% (roughly expected)
3.	With ECC enabled, General FFT is substantially faster than Hermitian FFT, which doesn’t make any sense
4.	With ECC enabled, Forward Hermitian and Inverse Hermitian FFT performance is substantially different (3.5x),  which again doesn’t make any sense

I know that ECC performance can largely depend on memory access patterns, which of course requires a deep understanding of the implementation... which I don't have yet. Naturally I'm willing to dive into the code and attempt to improve performance (then contribute to clFFT), but I'm not even sure where to begin with something like this. 

Any suggestions?

**Comment by pavanky** [comment]
Is this a problem with the library ? Isn't this more of an issue with the driver ?

**Comment by bragadeesh** [comment]
It is interesting to note that ECC makes a big difference for real FFTs. The difference in access pattern between complex FFT and real FFT is the hermitian storage. Because, only 1+N/2 elements are stored with hermitian format, consecutive batches start at non power-of-2 strides. In the 4096 case, it would be 2049 elements apart. I wonder if that causes this drop. Let me dig a little more into ECC caveats.

**Comment by keryell** [comment]
Bragadeesh> It is interesting to note that ECC makes a big
    Bragadeesh> difference for real FFTs.  The difference in access
    Bragadeesh> pattern between complex FFT and real FFT is the
    Bragadeesh> hermitian storage. Because, only 1+N/2 elements are
    Bragadeesh> stored with hermitian format, consecutive batches start
    Bragadeesh> at non power-of-2 strides. In the 4096 case, it would be
    Bragadeesh> 2049 elements apart. I wonder if that causes this drop.
    Bragadeesh> Let me dig a little more into ECC caveats.

I do not know how it is implemented on AMD GPU but my current
understanding is that when you allocate an ECC buffer, you have to be
sure there is no error when you read it later. That means that the
runtime needs to write all the memory to put it in a coherent state,
with a right matching between the data and the ECC part.

Without ECC, you do not need to initialize the buffer at all (well, if
you are not concerned by security issues, about reading some buffers
coming from the outer space and leaking confidential information).

So if you have an application that just write a very small part of ECC
buffers, the initialization of the memory will be preponderant in the
execution time...

**Comment by bragadeesh** [comment]
Thanks Ronan, if this is indeed the issue, that may mean the original buffers were not allocated with correct sizes. ljohnson1228 - are you correctly allocating only the minimum required hermitian output buffers or overallocating them?

**Comment by ljohnson1228** [comment]
Thanks for the prompt response. I'm not allocating any more memory than necessary in my application, but again the numbers above are for the clFFT benchmark (Client.exe).  I'm assuming it's only allocating as much memory as needed.

**Comment by ljohnson1228** [comment]
@pavanky - could be either as far as I'm concerned. I've seen a new driver shoot my ECC performance, but also a kernel with a particular (usually poor) memory access pattern fall victim to it as well. Seeing the complex-to-complex kernel not take a huge hit while the supposedly easier Hermitian makes me think it has to do with access pattern. I'm only speculating though.

**Comment by ljohnson1228** [comment]
@bragadeesh - did your digging reveal anything?

**Comment by bragadeesh** [comment]
We understand the issues now and at least R2C and C2R are fixed c03d7bb75d643707aa0ff77b081c3479eeacdb1c
