### ISSUE TITLE
Rename client executable to clFFT-client instead of Client

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clFFT#86]
A generic name like Client is very likely to shadow some other system utility. I suggest to use a similar naming convention as in clBLAS, i.e. client -> clFFT-client.

Here is the patch I am currently applying downstream to the Debian packaging:

```
Description: fix client executable name
Author: Ghislain Antony Vaillant <ghisvail@gmail.com>
Forwarded: not-needed
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/
--- a/src/client/CMakeLists.txt
+++ b/src/client/CMakeLists.txt
@@ -47,8 +47,8 @@
 
 target_link_libraries( Client clFFT ${Boost_LIBRARIES} ${OPENCL_LIBRARIES} ${DL_LIB} )
 
-set_target_properties( Client PROPERTIES VERSION ${CLFFT_VERSION} )
-set_target_properties( Client PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/staging" )
+#set_target_properties( Client PROPERTIES VERSION ${CLFFT_VERSION} )
+set_target_properties( Client PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/staging" OUTPUT_NAME clFFT-client)
 
 # CPack configuration; include the executable into the package
 install( TARGETS Client
```

This patch also removes the versioning of the binary, which looks unnecessary to me. Besides, it is not applied to the clBLAS client, so why in clFFT ? Feel free to re-use part or all of the patch, all the additional Debian specific code is licensed under the same terms as clFFT in order to ease collaboration.

Cheers,
Ghislain

**Comment by marbre** [comment]
Isn't this resolved in the develop branch with https://github.com/clMathLibraries/clFFT/pull/53?
Regards

Marius

**Comment by ghisvail** [comment]
It is, my bad for the duplicate.
