### ISSUE TITLE
Error -45 after successful init

### ISSUE THREAD

**Issue by MathiasMagnus** [clMathLibraries/clFFT#91]
I am writing up an infinitely simple clFFT example using batch and multi-GPU. I am subdividing my input manually (because internal multi-GPU is not implemented yet). I am creating a plan for every device seperately (as they are using different queues, naturally), and all of the plans are baked before trying to execute them. Executing result in error -45 (INVALID_PROGRAM_OBJECTS).

Files:

CMake: http://pastebin.com/XrAkSM9x
Header: http://pastebin.com/Bx17Zdwg
Source: http://pastebin.com/Dy5YLuur

Layout:

CMakeLists.txt
src/Source.cpp
inc/Header.hpp
cmake/Modules/FindclFFT.cmake

**Comment by kknox** [comment]
@MathiasMagnus 
Our corporate firewall blocks pastebin for whatever reason; could you post those files into a gist?  We have access to that.

**Comment by MathiasMagnus** [comment]
https://gist.github.com/anonymous/b640cf104291c331f81f

**Comment by MathiasMagnus** [comment]
Any reflections?

**Comment by kknox** [comment]
Our FFT guru is absorbed right now dealing with internal milestones; it may be a few days.

**Comment by MathiasMagnus** [comment]
C:\Users\nagy-_000> ping https://github.com/clMathLibraries/clFFT/issues/91

Pinging github.com [192.30.252.131] with 32 bytes of data:
Reply from 192.30.252.131: bytes=32 time=20+days TTL=54
Reply from 192.30.252.131: bytes=32 time=20+days TTL=54
Reply from 192.30.252.131: bytes=32 time=20+days TTL=54
Reply from 192.30.252.131: bytes=32 time=20+days TTL=54

Ping statistics for 192.30.252.131:
    Packets: Sent = 4, Received = 4, Lost = Definately (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = Whoaa, Maximum = Geeez, Average = Sheesh

**Comment by MathiasMagnus** [comment]
Closed the issue accidentally. My bad..

**Comment by bragadeesh** [comment]
I am closing this. I tried running this but the application crashed because of other things going wrong such as the line: clfftSetPlanBatchSize(plans.at(i), 128 / devices.size());
This is incorrect. Please simplify your code and make it plain C. 

We fixed the library long-back to allow usage of multi-GPU with the application doing the splitting and using separate queues with the library. It has worked correctly for other customers.

**Comment by MathiasMagnus** [comment]
That sounds nice on 'paper', but the truth I see is this:

clfftStatus clfftEnqueueTransform(
											clfftPlanHandle plHandle,
											clfftDirection dir,
											cl_uint numQueuesAndEvents,
											cl_command_queue* commQueues,
											cl_uint numWaitEvents,
											const cl_event* waitEvents,
											cl_event* outEvents,
											cl_mem* clInputBuffers,
											cl_mem* clOutputBuffers,
											cl_mem clTmpBuffers
											)
{
	cl_int status = CLFFT_SUCCESS;

	//	We do not currently support multiple command queues, which is necessary to support multi-gpu operations
	if( numQueuesAndEvents > 1 )
	{
		return CLFFT_NOTIMPLEMENTED;
	}
...
}

How exactly does that relate to "We fixed the library long-back to allow usage of multi-GPU with the application doing the splitting and using separate queues with the library. It has worked correctly for other customers."?

I have never used doxygen before, and I am having trouble building the documentation, but I doubt it would provide significantly more information on multi-GPU usage than the sources themselves. Could you please elaborate a little on how multi-GPU actually works? The hardcoded 128 in the source code should've been 'batch', as that is the variable I introduced later but did not refactor correctly. With that being correct, it still segfaults, but I doubt going plain C will help on removing bugs. The kind of C++ employed here is not that difficult. It's just that the actual way of invoking the function is not trivial.

**Comment by bragadeesh** [comment]
What I mean here is that the library can be used in a multi-GPU environment by an application, like you are trying to do. This has been tested before. But key thing here is that the application code is the one that has to divide the data correctly and then create and launch separate plans for each GPU. The library by itself does not have the capability to divide the problem and dispatch across multiple GPUs. For one plan, and a corresponding clfftEnqueueTransform call, the library knows only to use 1 GPU. But the application code is free to make multiple plans and corresponding separate calls to clfftEnqueueTransform for every GPU. I hope this makes it clear.

My support bandwidth is limited, so I asked for simplified repro code preferably in C. It will help me investigate this quicker, and hopefully resolve this to your benefit.

**Comment by MathiasMagnus** [comment]
I managed to track down the problem, which indeed was in my code. (Did not call resize on a vector of C handles I should've.) To counter such issues in the future, I started to wrap the few functions I need so they consume the cl.hpp entities (cl::CommandQueue and such).

Shall I raise the C++ bindings as a feature request for future poor souls who favor the C++ bindings of OpenCL?
