### ISSUE TITLE
instructions on compilation?

### ISSUE THREAD

**Issue by SaintDako** [clMathLibraries/clFFT#92]
hi, I'm a bit of a newbie with C++/C so I'm not too sure on how to get this running. I've tried two ways.

first way: downloading the binary, extracting it, and trying to link it. for example, if I have the extracted files in a folder called `clFFT`, and my file `main.c` (the example in the readme) is at the top level, then I would assume that I would run something like:

```
gcc -I./clFFT/include main.c -o main.out -lOpenCL -L./clFFT/lib64 -lclFFT
./main.out
```

this didn't work. I also tried compiling the git repo code using:

```
cmake .
cd src/
make
make install
```

and then running the same commands (with the directories changed a bit), and I get this error:

```
./main.out: error while loading shared libraries: libclFFT.so.2: cannot open shared object file: No such file or directory
```

any suggestions would be greatly appreciated!

**Comment by ghisvail** [comment]
Hi. You should probably ask your question on the relevant google groups [1], instead of opening an issue on Github.

[1] https://groups.google.com/forum/#!forum/clmath

**Comment by SaintDako** [comment]
thanks! got an answer (https://groups.google.com/forum/#!topic/clmath/p8Tw5PbmsrA )

for the record, I did the following:

```bash
git clone https://github.com/clMathLibraries/clFFT.git
cd clFFT
mkdir build
cd build
cmake ../src
make
make install
```

to run the code, update `LD_LIBRARY_PATH` as:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/some/path/to/clFFT/build/package/lib64
```

(where `clFFT` is the repository we just made, not necessarily a system-installed directory). change back to the directory with the file in it (I'm going to assume that the file is in the same directory as the clFFT directory), and run:

```
gcc -I./clFFT/build/package/include main.c -o main -lOpenCL -L./clFFT/build/package/lib64 -lclFFT
```

and it should compile and run correctly! :hamburger:
