### ISSUE TITLE
Build error with clFFT 2.6

### ISSUE THREAD

**Issue by k3ack3r** [clMathLibraries/clFFT#96]
[ 66%] Building CXX object library/CMakeFiles/clFFT.dir/action.cpp.obj
C:/msys64/home/Mars/clFFT-2.6/src/library/fft_binary_lookup.cpp: In member function 'bool FFTBinaryLookup::CacheEntry::exclusive_create()':
C:/msys64/home/Mars/clFFT-2.6/src/library/fft_binary_lookup.cpp:111:36: error: cannot convert 'const wchar_t*' to 'LPCSTR {aka const char*}' for argument '1' to 'void* CreateFileA(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE)'
                                NULL);
                                    ^
library/CMakeFiles/clFFT.dir/build.make:288: recipe for target 'library/CMakeFiles/clFFT.dir/fft_binary_lookup.cpp.obj' failed
make[2]: *** [library/CMakeFiles/clFFT.dir/fft_binary_lookup.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....

Using x86_64 MSYS2 with GCC 4.9.2, clFFT 2.4 compiles fine here.

**Comment by bragadeesh** [comment]
Please reopen if you have a solution for this and would like us to review and pull in through a PR
