### ISSUE TITLE
1D real-to-complex transform fails for lengths above 2048

### ISSUE THREAD

**Issue by SaintDako** [clMathLibraries/clFFT#98]
Doing a `CLFFT_REAL --> CLFFT_HERMITIAN_INTERLEAVED` transform.

Passes for `length = 2048` and `length = 1024` (presumably smaller powers of 2 as well)
Fails for `length = 4096` and larger powers of 2.

The error I get is `CLFFT_INVALID_WORK_GROUP_SIZE`. 

I peeked into the source code and threw print statements in there. When using `length = 4096` I get that my print statements are actually executed twice.

The first execution, I get:

```bash
# inside generator.stockham.cpp
fft_R = 4
fft_RCsimple = true
fft_inputLayout = real
fft_outputLayout = complex

# inside action.cpp
global work size = 1024
local  work size = 1024
```

While on the second execution, I get:

```bash
# inside generator.stockham.cpp
fft_R = 4
fft_RCsimple = false
fft_inputLayout = complex
fft_outputLayout = complex

# inside action.cpp
global work size = 1024
local  work size = 1024
global work size = 2049
local  work size = 2049
```

Note: I didn't make a mistake while writing that, it actually executes `action.cpp`'s print statements twice in the second execution.

It's obvious that the global work size of 2049 isn't gonna work. So what's going on here?

**Comment by bragadeesh** [comment]
I am unable to reproduce this on my end with an AMD W9100 card. I tried a different card (again AMD one) and could not see this problem. I suppose you are using Nvidia GPU from your post on the groups?

**Comment by SaintDako** [comment]
yes, I am (unfortunately) using a NVIDIA GPU. This seems like a very strange bug to happen from card to card.

**Comment by pavanky** [comment]
@SaintDako What GPU (Kepler / Fermi / something else) are you using ?

**Comment by SaintDako** [comment]
it's a GeForce GTX 960, so I believe it's the Maxwell architecture.

**Comment by pavanky** [comment]
Hmm, I just checked it using arrayfire opencl backend (which uses clFFT) for size 4096 x 4096 for both single and double precision. It works fine on GTX 680. I do not have a Maxwell GPU handy to test this out.

Can you post code about how you are using it ?

For reference, here is the code ArrayFire uses for real to complex transform: https://github.com/arrayfire/arrayfire/blob/devel/src/backend/opencl/fft.cpp#L241

**Comment by SaintDako** [comment]
I'll post the code over the next few days - I'm rewriting what I have as an example, as my supervisor doesn't want me to distribute the source. I have to get a presentation done for work by Friday, and I have an exam Friday night, so I'm trying to whip together the presentation and cram for the exam, and thus it will take me a bit.

**Comment by SaintDako** [comment]
Scratch that, I remembered I had an example that already does a real-to-complex transform, so I modified it to test it with FFTW as well: https://github.com/SaintDako/OpenCL-examples/blob/master/example05/main.c

This works for `N = 2048` (which is what is defined in the code) but fails for `N = 4096`.

**Comment by SaintDako** [comment]
update: this works for single precision, but not double precision.

ping @pavanky

**Comment by pavanky** [comment]
Ran our fftR2C<2> again with double precision on K20c for sizes up to 4096 x 4096 on the latest develop. No problems.

I even ran the sample gist code that you included here. It also runs successfully without any errors.

What driver are you on ? 

P.S. I am testing this on Linux.

**Comment by SaintDako** [comment]
from `nvidia-settings`:

```
NVIDIA Driver Version: 346.46
```

I'm running Ubuntu 12.04, but I think this will not work on the Ubuntu 14.04 machine I have access to that has a GTX 980. I am thinking this is a Maxwell-generation thing. Bizarre.

**Comment by pavanky** [comment]
The K20c machine is using the same driver. I do not think it is a problem with Maxwell. We have a first generation Maxwell I can try it on.

**Comment by pavanky** [comment]
Can you make sure you are building clFFT in release mode ?

**Comment by SaintDako** [comment]
How do I specify release mode? I run the following steps to install:

```
git clone https://github.com/clMathLibraries/clFFT.git
cd clFFT
mkdir build
cd build
cmake ../src
make
sudo make install
```

**Comment by pavanky** [comment]
@SaintDako That should default to Release mode. Can you check if your application is picking up the right clFFT ? It could be linking with another (older) version of clFFT present on the system.

**Comment by SaintDako** [comment]
Looking in `/usr/local/include/clFFT.version.h.`, I get `2.6.1` to be the version number.

Inside `/usr/local/lib64/`, there is `libclFFT.so.2.6.1`

**Comment by bragadeesh** [comment]
There was a kernel in the clFFT workflow that was producing global work-items that is non-multiple of local workitems (does not work of OpenCL 1.2 and earlier). This didn't cause an issue in many of the systems because the run-times have updated implementations adhering to OpenCL 2.0 spec that no longer has this requirement. 

I just made a checkin on the develop branch to address this. You can try building from that and see if it fixes the problem. Thanks.

**Comment by SaintDako** [comment]
Ah, I should say I'm using OpenCL 1.1. That's probably important. I'll take a look at the development branch though.

**Comment by pavanky** [comment]
The nvidia devices can do at most OpenCL 1.2 I am not sure how the error is not showing up for me.

I just tested this on 750 (Maxwell first gen) and can not reproduce the problem.

@SaintDako If you are seeing version 2.6, you are using master branch not develop! Can you try building the develop branch and test it again ? The version should read 2.7

**Comment by SaintDako** [comment]
That seemed to be the trick. I was indeed using the master branch, as `git clone` defaults to that. I made & installed on the develop branch and it worked out. I greatly appreciate this! My supervisor will be happy now. :beers:

**Comment by bragadeesh** [comment]
Nice to know it works :)
